# Generated by Django 4.2.7 on 2025-08-04 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_active_account",
            new_name="is_active",
        ),
    ]
