# Generated by Django 4.2.7 on 2025-08-07 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_is_active_account_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="admin_approval_status",
            field=models.CharField(
                choices=[("pending", "待审批"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="approved",
                help_text="仅管理员角色需要审批",
                max_length=20,
                verbose_name="管理员审批状态",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="选填，不可与他人相同",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="网名",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator("^[\\d\\-\\+\\(\\)\\s]+$")
                ],
                verbose_name="手机号码",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                ],
                default="student",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
        migrations.CreateModel(
            name="RoleApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("parent", "家长"),
                            ("teacher", "自由老师"),
                            ("admin", "管理员"),
                        ],
                        max_length=20,
                        verbose_name="申请角色",
                    ),
                ),
                (
                    "current_role",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("parent", "家长"),
                            ("teacher", "自由老师"),
                            ("admin", "管理员"),
                        ],
                        max_length=20,
                        verbose_name="当前角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, max_length=500, verbose_name="申请理由"),
                ),
                (
                    "admin_comment",
                    models.TextField(blank=True, max_length=500, verbose_name="管理员备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色审批",
                "verbose_name_plural": "角色审批管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
