# Generated by Django 4.2.23 on 2025-08-21 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_roleapproval_roleextension_rolelevel_roletemplate_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roleuser",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="roleuser",
            name="role_level",
        ),
        migrations.RemoveField(
            model_name="roleuser",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userextension",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userextension",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="userextension",
            name="role_extension",
        ),
        migrations.RemoveField(
            model_name="userextension",
            name="role_user",
        ),
        migrations.DeleteModel(
            name="RoleLevel",
        ),
        migrations.DeleteModel(
            name="RoleUser",
        ),
        migrations.DeleteModel(
            name="UserExtension",
        ),
    ]
