# Generated by Django 4.2.23 on 2025-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_deprecated_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                    ("project_assistant", "项目助理"),
                    ("project_manager_assistant", "项目管理助理"),
                ],
                default="student",
                max_length=30,
                verbose_name="用户角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="current_role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                    ("project_assistant", "项目助理"),
                    ("project_manager_assistant", "项目管理助理"),
                ],
                max_length=30,
                verbose_name="当前角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="requested_role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                    ("project_assistant", "项目助理"),
                    ("project_manager_assistant", "项目管理助理"),
                ],
                max_length=30,
                verbose_name="申请角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleextension",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                    ("project_assistant", "项目助理"),
                    ("project_manager_assistant", "项目管理助理"),
                ],
                help_text="绑定的用户角色",
                max_length=30,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="roletemplate",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                    ("project_assistant", "项目助理"),
                    ("project_manager_assistant", "项目管理助理"),
                ],
                help_text="绑定的用户角色",
                max_length=30,
                unique=True,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleusergroup",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                    ("project_assistant", "项目助理"),
                    ("project_manager_assistant", "项目管理助理"),
                ],
                help_text="绑定的用户角色",
                max_length=30,
                verbose_name="绑定角色",
            ),
        ),
    ]
