# Generated by Django 4.2.7 on 2025-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_customuser_admin_approval_status_customuser_nickname_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningprofile",
            name="completed_lessons",
            field=models.PositiveIntegerField(verbose_name="完成课程数"),
        ),
        migrations.AlterField(
            model_name="learningprofile",
            name="current_streak",
            field=models.PositiveIntegerField(verbose_name="连续学习天数"),
        ),
        migrations.AlterField(
            model_name="learningprofile",
            name="max_streak",
            field=models.PositiveIntegerField(verbose_name="最长连续学习天数"),
        ),
        migrations.AlterField(
            model_name="learningprofile",
            name="total_study_time",
            field=models.PositiveIntegerField(verbose_name="总学习时长(分钟)"),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="login_success",
            field=models.BooleanField(verbose_name="登录成功"),
        ),
    ]
