# Generated by Django 4.2.7 on 2025-08-07 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_learningprofile_completed_lessons_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="角色标识，如student、teacher等",
                        max_length=50,
                        verbose_name="角色",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="字段的内部名称", max_length=50, verbose_name="字段名称"
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        help_text="显示给用户的字段名称", max_length=100, verbose_name="字段标签"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "文本字段"),
                            ("textarea", "多行文本"),
                            ("number", "数字字段"),
                            ("email", "邮箱字段"),
                            ("date", "日期字段"),
                            ("choice", "选择字段"),
                            ("boolean", "布尔字段"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="字段类型",
                    ),
                ),
                (
                    "field_choices",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式的选择项，仅当字段类型为choice时使用",
                        verbose_name="选择项",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必填"),
                ),
                (
                    "help_text",
                    models.CharField(blank=True, max_length=200, verbose_name="帮助文本"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色增项配置",
                "verbose_name_plural": "角色增项配置管理",
                "ordering": ["role", "sort_order", "field_name"],
                "unique_together": {("role", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="UserExtensionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_value", models.TextField(blank=True, verbose_name="字段值")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "role_extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.roleextension",
                        verbose_name="角色增项",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户增项数据",
                "verbose_name_plural": "用户增项数据管理",
                "unique_together": {("user", "role_extension")},
            },
        ),
        migrations.CreateModel(
            name="AdminExtensionProxy",
            fields=[],
            options={
                "verbose_name": "管理员账号增项",
                "verbose_name_plural": "管理员账号增项",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.userextensiondata",),
        ),
        migrations.CreateModel(
            name="ParentExtensionProxy",
            fields=[],
            options={
                "verbose_name": "家长账号增项",
                "verbose_name_plural": "家长账号增项",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.userextensiondata",),
        ),
        migrations.CreateModel(
            name="StudentExtensionProxy",
            fields=[],
            options={
                "verbose_name": "学生账号增项",
                "verbose_name_plural": "学生账号增项",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.userextensiondata",),
        ),
        migrations.CreateModel(
            name="TeacherExtensionProxy",
            fields=[],
            options={
                "verbose_name": "教师账号增项",
                "verbose_name_plural": "教师账号增项",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.userextensiondata",),
        ),
    ]
