# Generated by Django 4.2.7 on 2025-08-07 23:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_roleextension_userextensiondata_adminextensionproxy_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminExtensionProxy",
        ),
        migrations.DeleteModel(
            name="ParentExtensionProxy",
        ),
        migrations.DeleteModel(
            name="StudentExtensionProxy",
        ),
        migrations.DeleteModel(
            name="TeacherExtensionProxy",
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="roleextension",
            name="show_in_backend_admin",
            field=models.BooleanField(
                default=True, help_text="是否在后台管理界面显示此字段", verbose_name="后台管理显示"
            ),
        ),
        migrations.AddField(
            model_name="roleextension",
            name="show_in_frontend_register",
            field=models.BooleanField(
                default=True, help_text="是否在前台注册页面显示此字段", verbose_name="前台注册显示"
            ),
        ),
        migrations.AddField(
            model_name="roleextension",
            name="show_in_profile",
            field=models.BooleanField(
                default=True, help_text="是否在个人资料页面显示此字段", verbose_name="个人资料显示"
            ),
        ),
        migrations.AlterField(
            model_name="roleextension",
            name="field_choices",
            field=models.TextField(
                blank=True,
                help_text='JSON格式的选择项，仅当字段类型为choice时使用，格式：[["value1", "显示名1"], ["value2", "显示名2"]]',
                verbose_name="选择项",
            ),
        ),
        migrations.AlterField(
            model_name="roleextension",
            name="field_name",
            field=models.CharField(
                help_text="字段的内部名称，用于API和数据库存储", max_length=50, verbose_name="字段名称"
            ),
        ),
        migrations.AlterField(
            model_name="roleextension",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "文本字段"),
                    ("textarea", "多行文本"),
                    ("number", "数字字段"),
                    ("email", "邮箱字段"),
                    ("date", "日期字段"),
                    ("choice", "选择字段"),
                    ("boolean", "布尔字段"),
                    ("url", "URL字段"),
                    ("phone", "电话字段"),
                ],
                default="text",
                max_length=20,
                verbose_name="字段类型",
            ),
        ),
        migrations.AlterField(
            model_name="roleextension",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                ],
                help_text="绑定的用户角色",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleextension",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="字段显示顺序，数字越小越靠前", verbose_name="排序"
            ),
        ),
    ]
