# Generated by Django 4.2.7 on 2025-08-08 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_delete_adminextensionproxy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="用户组的显示名称", max_length=100, verbose_name="组名称"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("parent", "家长"),
                            ("teacher", "自由老师"),
                            ("admin", "管理员"),
                        ],
                        help_text="绑定的用户角色",
                        max_length=20,
                        verbose_name="绑定角色",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="用户组的详细描述", verbose_name="组描述"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_role_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="选择该角色下的用户加入此组",
                        limit_choices_to={"is_active": True},
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="组成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色用户组",
                "verbose_name_plural": "角色用户组管理",
                "ordering": ["role", "name"],
            },
        ),
    ]
