# Generated by Django 4.2.7 on 2025-08-08 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_roleusergroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("parent", "家长"),
                            ("teacher", "自由老师"),
                            ("admin", "管理员"),
                        ],
                        help_text="角色类型",
                        max_length=20,
                        unique=True,
                        verbose_name="角色类型",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        help_text="角色显示名称", max_length=50, verbose_name="角色名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="角色的详细描述", verbose_name="角色描述"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="显示顺序", verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色级别",
                "verbose_name_plural": "角色级别管理",
                "ordering": ["sort_order", "role"],
            },
        ),
        migrations.CreateModel(
            name="RoleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="用户在该角色下的备注信息", verbose_name="备注"
                    ),
                ),
                (
                    "role_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_users",
                        to="accounts.rolelevel",
                        verbose_name="所属角色",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_user_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色用户",
                "verbose_name_plural": "角色用户管理",
                "ordering": ["role_level", "user__username"],
                "unique_together": {("role_level", "user")},
            },
        ),
        migrations.AlterModelOptions(
            name="roleapproval",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "注册管理员审批",
                "verbose_name_plural": "注册管理员审批",
            },
        ),
        migrations.AlterModelOptions(
            name="roleusergroup",
            options={
                "ordering": ["role", "name"],
                "verbose_name": "角色所辖用户",
                "verbose_name_plural": "角色所辖用户",
            },
        ),
        migrations.AlterModelOptions(
            name="userextensiondata",
            options={"verbose_name": "角色所辖用户增项", "verbose_name_plural": "角色所辖用户增项"},
        ),
        migrations.CreateModel(
            name="UserExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_value",
                    models.TextField(
                        blank=True, help_text="增项字段的值", verbose_name="字段值"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_extensions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "role_extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.roleextension",
                        verbose_name="增项配置",
                    ),
                ),
                (
                    "role_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_extensions",
                        to="accounts.roleuser",
                        verbose_name="角色用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户增项",
                "verbose_name_plural": "用户增项管理",
                "ordering": ["role_user", "role_extension__sort_order"],
                "unique_together": {("role_user", "role_extension")},
            },
        ),
    ]
