# Generated by Django 4.2.7 on 2025-08-08 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_add_role_template_system"),
        ("accounts", "0009_remove_parent_fields"),
    ]

    operations = []
