# Generated by Django 4.2.7 on 2025-08-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_merge_20250808_1752"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminUserProxy",
        ),
        migrations.DeleteModel(
            name="ParentUserProxy",
        ),
        migrations.DeleteModel(
            name="StudentUserProxy",
        ),
        migrations.DeleteModel(
            name="TeacherUserProxy",
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AlterModelOptions(
            name="roleextension",
            options={
                "ordering": ["role", "sort_order", "field_name"],
                "verbose_name": "角色增项配置",
                "verbose_name_plural": "角色增项配置",
            },
        ),
        migrations.AlterModelOptions(
            name="roleusergroup",
            options={
                "ordering": ["role", "name"],
                "verbose_name": "角色用户组",
                "verbose_name_plural": "角色用户组",
            },
        ),
        migrations.AlterModelOptions(
            name="userextension",
            options={
                "ordering": ["role_user", "role_extension__sort_order"],
                "verbose_name": "用户增项",
                "verbose_name_plural": "用户增项",
            },
        ),
        migrations.AlterModelOptions(
            name="userextensiondata",
            options={"verbose_name": "用户增项数据", "verbose_name_plural": "用户增项数据"},
        ),
        migrations.AlterField(
            model_name="roletemplate",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                ],
                help_text="绑定的用户角色",
                max_length=20,
                unique=True,
                verbose_name="角色",
            ),
        ),
    ]
