# Generated by Django 4.2.7 on 2025-08-08 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_merge_20250808_2024"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "用户", "verbose_name_plural": "用户管理"},
        ),
        migrations.AlterModelOptions(
            name="roleextension",
            options={
                "ordering": ["role", "sort_order", "field_name"],
                "verbose_name": "角色增项配置",
                "verbose_name_plural": "角色增项配置管理",
            },
        ),
        migrations.AlterModelOptions(
            name="roleusergroup",
            options={
                "ordering": ["role", "name"],
                "verbose_name": "角色所辖用户",
                "verbose_name_plural": "角色所辖用户",
            },
        ),
        migrations.AlterModelOptions(
            name="userextension",
            options={
                "ordering": ["role_user", "role_extension__sort_order"],
                "verbose_name": "用户增项",
                "verbose_name_plural": "用户增项管理",
            },
        ),
        migrations.AlterModelOptions(
            name="userextensiondata",
            options={"verbose_name": "角色所辖用户增项", "verbose_name_plural": "角色所辖用户增项"},
        ),
    ]
