# Generated by Django 4.2.7 on 2025-08-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0013_alter_customuser_options_alter_roleextension_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                ],
                default="student",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="current_role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                ],
                max_length=20,
                verbose_name="当前角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="requested_role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                ],
                max_length=20,
                verbose_name="申请角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleextension",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                ],
                help_text="绑定的用户角色",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="rolelevel",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                ],
                help_text="角色类型",
                max_length=20,
                unique=True,
                verbose_name="角色类型",
            ),
        ),
        migrations.AlterField(
            model_name="roletemplate",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                ],
                help_text="绑定的用户角色",
                max_length=20,
                unique=True,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="roleusergroup",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                ],
                help_text="绑定的用户角色",
                max_length=20,
                verbose_name="绑定角色",
            ),
        ),
    ]
