# Generated by Django 4.2.7 on 2025-08-04 11:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="来源名称")),
                ("description", models.TextField(blank=True, verbose_name="来源描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "词库导入来源",
                "verbose_name_plural": "词库导入来源",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WordResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="资源名称")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("audio", "音频"),
                            ("video", "视频"),
                            ("image", "图片"),
                            ("pdf", "PDF文档"),
                            ("markdown", "Markdown文档"),
                            ("text", "文本文档"),
                            ("url", "网络链接"),
                        ],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="word_resources/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "mp3",
                                    "wav",
                                    "mp4",
                                    "avi",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "pdf",
                                    "md",
                                    "txt",
                                ]
                            )
                        ],
                        verbose_name="文件",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="网络链接")),
                ("description", models.TextField(blank=True, verbose_name="资源描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "单词资源",
                "verbose_name_plural": "单词资源",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, verbose_name="单词")),
                (
                    "phonetic",
                    models.CharField(blank=True, max_length=100, verbose_name="音标"),
                ),
                ("definition", models.TextField(blank=True, verbose_name="释义")),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("名词", "名词"),
                            ("动词", "动词"),
                            ("形容词", "形容词"),
                            ("副词", "副词"),
                            ("代词", "代词"),
                            ("数词", "数词"),
                            ("冠词", "冠词"),
                            ("介词", "介词"),
                            ("连词", "连词"),
                            ("感叹词", "感叹词"),
                            ("缩写词", "缩写词"),
                            ("短语", "短语"),
                            ("句子", "句子"),
                            ("其他", "其他"),
                        ],
                        max_length=50,
                        verbose_name="词性",
                    ),
                ),
                ("example", models.TextField(blank=True, verbose_name="例句")),
                ("note", models.TextField(blank=True, verbose_name="笔记")),
                (
                    "is_learned",
                    models.BooleanField(default=False, verbose_name="是否已学过"),
                ),
                (
                    "learned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="学习时间"),
                ),
                (
                    "mastery_level",
                    models.IntegerField(
                        default=0, help_text="0-100的掌握程度评分", verbose_name="掌握程度"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="用逗号分隔多个标签",
                        max_length=200,
                        verbose_name="标签",
                    ),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[
                            (1, "等级1"),
                            (2, "等级2"),
                            (3, "等级3"),
                            (4, "等级4"),
                            (5, "等级5"),
                        ],
                        default=1,
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "resources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="words",
                        to="words.wordresource",
                        verbose_name="绑定资源",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词",
                "verbose_name_plural": "单词",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="列表名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                ("word_count", models.IntegerField(default=0, verbose_name="单词数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary_lists",
                        to="words.vocabularysource",
                        verbose_name="词库来源",
                    ),
                ),
            ],
            options={
                "verbose_name": "词库列表",
                "verbose_name_plural": "词库列表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="当前连续天数"),
                ),
                (
                    "longest_streak",
                    models.IntegerField(default=0, verbose_name="最长连续天数"),
                ),
                (
                    "last_activity_date",
                    models.DateField(auto_now=True, verbose_name="最后活动日期"),
                ),
                (
                    "total_words_learned",
                    models.IntegerField(default=0, verbose_name="总学习单词数"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_streak",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习记录",
                "verbose_name_plural": "学习记录",
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_duration",
                    models.DurationField(blank=True, null=True, verbose_name="学习时长"),
                ),
                ("words_count", models.IntegerField(default=0, verbose_name="学习单词数")),
                (
                    "accuracy_rate",
                    models.FloatField(
                        default=0.0, help_text="0.0-1.0之间的正确率", verbose_name="正确率"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "words_studied",
                    models.ManyToManyField(
                        related_name="study_sessions",
                        to="words.word",
                        verbose_name="学习的单词",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习会话",
                "verbose_name_plural": "学习会话",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportedVocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, verbose_name="单词")),
                (
                    "phonetic",
                    models.CharField(blank=True, max_length=100, verbose_name="音标"),
                ),
                ("definition", models.TextField(blank=True, verbose_name="释义")),
                (
                    "part_of_speech",
                    models.CharField(blank=True, max_length=50, verbose_name="词性"),
                ),
                (
                    "textbook_version",
                    models.CharField(blank=True, max_length=50, verbose_name="教材版本"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "一年级"),
                            ("2", "二年级"),
                            ("3", "三年级"),
                            ("4", "四年级"),
                            ("5", "五年级"),
                            ("6", "六年级"),
                            ("7", "初一"),
                            ("8", "初二"),
                            ("9", "初三"),
                            ("10", "高一"),
                            ("11", "高二"),
                            ("12", "高三"),
                        ],
                        max_length=20,
                        verbose_name="年级",
                    ),
                ),
                ("example", models.TextField(blank=True, verbose_name="例句")),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "has_conflict",
                    models.BooleanField(default=False, verbose_name="有冲突"),
                ),
                (
                    "conflict_data",
                    models.JSONField(blank=True, default=dict, verbose_name="冲突数据"),
                ),
                (
                    "conflict_resolved",
                    models.BooleanField(default=False, verbose_name="冲突已处理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "vocabulary_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_words",
                        to="words.vocabularylist",
                        verbose_name="词库列表",
                    ),
                ),
            ],
            options={
                "verbose_name": "导入的单词",
                "verbose_name_plural": "导入的单词",
                "ordering": ["word"],
            },
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["user", "word"], name="words_word_user_id_b84db4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["user", "is_learned"], name="words_word_user_id_2ec6f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["difficulty_level"], name="words_word_difficu_11607f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("user", "word")},
        ),
        migrations.AddIndex(
            model_name="importedvocabulary",
            index=models.Index(fields=["word"], name="words_impor_word_75a7cd_idx"),
        ),
        migrations.AddIndex(
            model_name="importedvocabulary",
            index=models.Index(
                fields=["vocabulary_list", "word"],
                name="words_impor_vocabul_045fa7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importedvocabulary",
            index=models.Index(
                fields=["has_conflict"], name="words_impor_has_con_3fe16a_idx"
            ),
        ),
    ]
