# Generated by Django 4.2.7 on 2025-08-10 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordGradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(help_text="分级等级，从1开始", verbose_name="等级"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="等级名称")),
                ("description", models.TextField(blank=True, verbose_name="等级描述")),
                ("min_difficulty", models.IntegerField(default=1, verbose_name="最低难度")),
                ("max_difficulty", models.IntegerField(default=5, verbose_name="最高难度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "单词分级等级设置",
                "verbose_name_plural": "单词分级等级设置",
                "ordering": ["grader", "level"],
            },
        ),
        migrations.CreateModel(
            name="WordGrader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分级方案名称")),
                ("description", models.TextField(blank=True, verbose_name="分级方案描述")),
                (
                    "grade_count",
                    models.IntegerField(
                        default=5, help_text="设置分级的数量", verbose_name="分级数量"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "单词分级器",
                "verbose_name_plural": "单词分级器",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WordSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="单词集的名称，必填且不能重复", max_length=100, verbose_name="单词集名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                ("word_count", models.IntegerField(default=0, verbose_name="单词数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "单词集",
                "verbose_name_plural": "单词集",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="importedvocabulary",
            name="vocabulary_list",
        ),
        migrations.RemoveField(
            model_name="studysession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="studysession",
            name="words_studied",
        ),
        migrations.RemoveField(
            model_name="userstreak",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="vocabularysource",
            options={
                "ordering": ["name"],
                "verbose_name": "词库导入来源设置",
                "verbose_name_plural": "词库导入来源设置",
            },
        ),
        migrations.AlterModelOptions(
            name="wordresource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "单词配套资源",
                "verbose_name_plural": "单词配套资源",
            },
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_user_id_b84db4_idx",
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_user_id_2ec6f9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="word",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "一年级"),
                    ("2", "二年级"),
                    ("3", "三年级"),
                    ("4", "四年级"),
                    ("5", "五年级"),
                    ("6", "六年级"),
                    ("7", "初一"),
                    ("8", "初二"),
                    ("9", "初三"),
                    ("10", "高一"),
                    ("11", "高二"),
                    ("12", "高三"),
                ],
                max_length=20,
                verbose_name="年级",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="has_multiple_versions",
            field=models.BooleanField(
                default=False, help_text="该单词是否有多个版本", verbose_name="是否含有多版本"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="parent_word",
            field=models.ForeignKey(
                blank=True,
                help_text="指向主单词，如果为空则表示这是主单词",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="words.word",
                verbose_name="主单词",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="textbook_version",
            field=models.CharField(blank=True, max_length=50, verbose_name="教材版本"),
        ),
        migrations.AddField(
            model_name="word",
            name="version_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="存储版本相关的元数据", verbose_name="版本数据"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="version_number",
            field=models.IntegerField(
                default=1, help_text="单词的版本号，从1开始", verbose_name="版本号"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="vocabulary_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to="words.vocabularylist",
                verbose_name="词库列表",
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(fields=["word"], name="words_word_word_a2cf21_idx"),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["vocabulary_list", "word"], name="words_word_vocabul_1742cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["has_multiple_versions"], name="words_word_has_mul_2b3668_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["version_number"], name="words_word_version_ab1125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["parent_word"], name="words_word_parent__b2ea82_idx"
            ),
        ),
        migrations.DeleteModel(
            name="ImportedVocabulary",
        ),
        migrations.DeleteModel(
            name="StudySession",
        ),
        migrations.DeleteModel(
            name="UserStreak",
        ),
        migrations.AddField(
            model_name="wordset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_word_sets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="wordset",
            name="words",
            field=models.ManyToManyField(
                blank=True, related_name="word_sets", to="words.word", verbose_name="单词"
            ),
        ),
        migrations.AddField(
            model_name="wordgrader",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_graders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="wordgradelevel",
            name="grader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_levels",
                to="words.wordgrader",
                verbose_name="分级器",
            ),
        ),
        migrations.AddField(
            model_name="wordgradelevel",
            name="word_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grade_levels",
                to="words.wordset",
                verbose_name="绑定单词集",
            ),
        ),
        migrations.RemoveField(
            model_name="word",
            name="is_learned",
        ),
        migrations.RemoveField(
            model_name="word",
            name="user",
        ),
        migrations.AddIndex(
            model_name="wordset",
            index=models.Index(fields=["name"], name="words_words_name_b5015e_idx"),
        ),
        migrations.AddIndex(
            model_name="wordset",
            index=models.Index(
                fields=["created_by"], name="words_words_created_669394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordset",
            index=models.Index(
                fields=["is_public"], name="words_words_is_publ_610ec6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordset",
            index=models.Index(
                fields=["name", "created_by"], name="words_words_name_c0ae64_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wordset",
            unique_together={("name", "created_by")},
        ),
        migrations.AddIndex(
            model_name="wordgrader",
            index=models.Index(fields=["name"], name="words_wordg_name_32499c_idx"),
        ),
        migrations.AddIndex(
            model_name="wordgrader",
            index=models.Index(
                fields=["is_active"], name="words_wordg_is_acti_e11920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordgradelevel",
            index=models.Index(
                fields=["grader", "level"], name="words_wordg_grader__a32ff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordgradelevel",
            index=models.Index(
                fields=["word_set"], name="words_wordg_word_se_67081f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wordgradelevel",
            unique_together={("grader", "level")},
        ),
    ]
