# Generated by Django 4.2.7 on 2025-08-04 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("keep_original", "保留原始"),
                            ("use_imported", "使用导入"),
                            ("merge", "合并"),
                            ("skip", "跳过"),
                            ("manual", "手动处理"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="解决方式",
                    ),
                ),
                (
                    "resolution_data",
                    models.JSONField(blank=True, default=dict, verbose_name="解决数据"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "existing_word",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_resolutions",
                        to="words.word",
                        verbose_name="现有单词",
                    ),
                ),
                (
                    "imported_vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="words.importedvocabulary",
                        verbose_name="导入词汇",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="解决人",
                    ),
                ),
            ],
            options={
                "verbose_name": "冲突解决记录",
                "verbose_name_plural": "冲突解决记录",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["imported_vocabulary"],
                        name="words_confl_importe_bfde4a_idx",
                    ),
                    models.Index(
                        fields=["resolution_type"],
                        name="words_confl_resolut_ff072b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="words_confl_created_c37205_idx"
                    ),
                ],
            },
        ),
    ]
