# Generated by Django 4.2.7 on 2025-08-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0002_wordgradelevel_wordgrader_wordset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="book_volume",
            field=models.CharField(
                blank=True, help_text="如：三上、三下、四上等", max_length=20, verbose_name="册别"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="如：Unit 1、Unit 2等",
                max_length=20,
                verbose_name="单元",
            ),
        ),
    ]
