# Generated by Django 4.2.7 on 2025-08-04 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0002_conflictresolution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importedvocabulary",
            name="vocabulary_list",
        ),
        migrations.AlterModelOptions(
            name="conflictresolution",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "单词导入冲突管理",
                "verbose_name_plural": "单词导入冲突管理",
            },
        ),
        migrations.RemoveIndex(
            model_name="conflictresolution",
            name="words_confl_importe_bfde4a_idx",
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_user_id_2ec6f9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="conflictresolution",
            name="existing_word",
        ),
        migrations.RemoveField(
            model_name="conflictresolution",
            name="imported_vocabulary",
        ),
        migrations.AddField(
            model_name="conflictresolution",
            name="conflicting_word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicting_resolutions",
                to="words.word",
                verbose_name="冲突对象",
            ),
        ),
        migrations.AddField(
            model_name="conflictresolution",
            name="is_resolved",
            field=models.BooleanField(default=False, verbose_name="是否已解决"),
        ),
        migrations.AddField(
            model_name="conflictresolution",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
        ),
        migrations.AddField(
            model_name="conflictresolution",
            name="word",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflict_resolutions",
                to="words.word",
                verbose_name="冲突单词",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="conflict_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="冲突数据"),
        ),
        migrations.AddField(
            model_name="word",
            name="conflict_resolved",
            field=models.BooleanField(default=False, verbose_name="冲突已处理"),
        ),
        migrations.AddField(
            model_name="word",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "一年级"),
                    ("2", "二年级"),
                    ("3", "三年级"),
                    ("4", "四年级"),
                    ("5", "五年级"),
                    ("6", "六年级"),
                    ("7", "初一"),
                    ("8", "初二"),
                    ("9", "初三"),
                    ("10", "高一"),
                    ("11", "高二"),
                    ("12", "高三"),
                ],
                max_length=20,
                verbose_name="年级",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="has_conflict",
            field=models.BooleanField(default=False, verbose_name="有冲突"),
        ),
        migrations.AddField(
            model_name="word",
            name="is_variant",
            field=models.BooleanField(default=False, verbose_name="是否为变体"),
        ),
        migrations.AddField(
            model_name="word",
            name="parent_word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="words.word",
                verbose_name="父单词",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="textbook_version",
            field=models.CharField(blank=True, max_length=50, verbose_name="教材版本"),
        ),
        migrations.AddField(
            model_name="word",
            name="vocabulary_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to="words.vocabularylist",
                verbose_name="词库列表",
            ),
        ),
        migrations.AlterField(
            model_name="conflictresolution",
            name="resolution_type",
            field=models.CharField(
                choices=[
                    ("keep_original", "保留原始"),
                    ("keep_imported", "保留导入"),
                    ("merge_variant", "合并为变体"),
                    ("manual", "手动处理"),
                ],
                default="manual",
                max_length=20,
                verbose_name="解决方式",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_words",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
        migrations.AddIndex(
            model_name="conflictresolution",
            index=models.Index(fields=["word"], name="words_confl_word_id_4af764_idx"),
        ),
        migrations.AddIndex(
            model_name="conflictresolution",
            index=models.Index(
                fields=["is_resolved"], name="words_confl_is_reso_6524d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(fields=["word"], name="words_word_word_a2cf21_idx"),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["vocabulary_list", "word"], name="words_word_vocabul_1742cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["has_conflict"], name="words_word_has_con_613e5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["is_variant"], name="words_word_is_vari_ca4ae4_idx"
            ),
        ),
        migrations.DeleteModel(
            name="ImportedVocabulary",
        ),
    ]
