# Generated by Django 4.2.7 on 2025-08-04 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0003_remove_importedvocabulary_vocabulary_list_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="单词集名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                ("word_count", models.IntegerField(default=0, verbose_name="单词数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_word_sets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True,
                        related_name="word_sets",
                        to="words.word",
                        verbose_name="单词",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词集",
                "verbose_name_plural": "单词集",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WordGrader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分级方案名称")),
                ("description", models.TextField(blank=True, verbose_name="分级方案描述")),
                (
                    "grade_count",
                    models.IntegerField(
                        default=5, help_text="设置分级的数量", verbose_name="分级数量"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_graders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词分级器",
                "verbose_name_plural": "单词分级器",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WordGradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(help_text="分级等级，从1开始", verbose_name="等级"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="等级名称")),
                ("description", models.TextField(blank=True, verbose_name="等级描述")),
                ("min_difficulty", models.IntegerField(default=1, verbose_name="最低难度")),
                ("max_difficulty", models.IntegerField(default=5, verbose_name="最高难度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "grader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_levels",
                        to="words.wordgrader",
                        verbose_name="分级器",
                    ),
                ),
                (
                    "word_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_levels",
                        to="words.wordset",
                        verbose_name="绑定单词集",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词分级等级",
                "verbose_name_plural": "单词分级等级",
                "ordering": ["grader", "level"],
            },
        ),
        migrations.AddIndex(
            model_name="wordset",
            index=models.Index(fields=["name"], name="words_words_name_b5015e_idx"),
        ),
        migrations.AddIndex(
            model_name="wordset",
            index=models.Index(
                fields=["created_by"], name="words_words_created_669394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordset",
            index=models.Index(
                fields=["is_public"], name="words_words_is_publ_610ec6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordgrader",
            index=models.Index(fields=["name"], name="words_wordg_name_32499c_idx"),
        ),
        migrations.AddIndex(
            model_name="wordgrader",
            index=models.Index(
                fields=["is_active"], name="words_wordg_is_acti_e11920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordgradelevel",
            index=models.Index(
                fields=["grader", "level"], name="words_wordg_grader__a32ff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordgradelevel",
            index=models.Index(
                fields=["word_set"], name="words_wordg_word_se_67081f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wordgradelevel",
            unique_together={("grader", "level")},
        ),
    ]
