# Generated by Django 4.2.23 on 2025-08-18 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0003_word_book_volume_word_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="import_batch_id",
            field=models.CharField(
                blank=True,
                help_text="同一次导入的批次标识",
                max_length=100,
                verbose_name="导入批次ID",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="import_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="存储导入时的额外信息", verbose_name="导入元数据"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="import_source",
            field=models.ForeignKey(
                blank=True,
                help_text="记录该单词的导入来源",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_words",
                to="words.vocabularysource",
                verbose_name="导入来源",
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["import_source"], name="words_word_import__01e6be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["import_batch_id"], name="words_word_import__fcebf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["word", "import_source"], name="words_word_word_2e8399_idx"
            ),
        ),
    ]
