# Generated by Django 4.2.7 on 2025-08-04 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0004_wordset_wordgrader_wordgradelevel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordset",
            name="name",
            field=models.CharField(
                help_text="单词集的名称，必填且不能重复", max_length=100, verbose_name="单词集名称"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wordset",
            unique_together={("name", "created_by")},
        ),
        migrations.AddIndex(
            model_name="wordset",
            index=models.Index(
                fields=["name", "created_by"], name="words_words_name_c0ae64_idx"
            ),
        ),
    ]
