# Generated by Django 4.2.23 on 2025-08-18 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0004_word_import_batch_id_word_import_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_difficu_11607f_idx",
        ),
        migrations.RemoveField(
            model_name="word",
            name="difficulty_level",
        ),
        migrations.RemoveField(
            model_name="word",
            name="mastery_level",
        ),
    ]
