# Generated by Django 4.2.7 on 2025-08-04 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0005_alter_wordset_name_alter_wordset_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstreak",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="wordresource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "单词配套资源",
                "verbose_name_plural": "单词配套资源",
            },
        ),
        migrations.DeleteModel(
            name="StudySession",
        ),
        migrations.DeleteModel(
            name="UserStreak",
        ),
    ]
