# Generated by Django 4.2.23 on 2025-08-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0005_remove_difficulty_mastery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularysource",
            name="auto_create_lists",
            field=models.BooleanField(
                default=True, help_text="是否自动创建词库列表", verbose_name="自动创建词库列表"
            ),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="是否允许从该来源导入", verbose_name="是否启用"
            ),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="last_import_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后导入时间"),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="last_import_batch_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="最后导入批次ID"),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="last_import_file_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="最后导入文件名"),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="last_import_word_count",
            field=models.IntegerField(default=0, verbose_name="最后导入单词数"),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="total_duplicate_words",
            field=models.IntegerField(
                default=0, help_text="该来源重复的单词数", verbose_name="重复单词数"
            ),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="total_imports",
            field=models.IntegerField(
                default=0, help_text="该来源的总导入次数", verbose_name="总导入次数"
            ),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="total_new_words",
            field=models.IntegerField(
                default=0, help_text="该来源新增的单词数", verbose_name="新增单词数"
            ),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="total_version_words",
            field=models.IntegerField(
                default=0, help_text="该来源创建的版本单词数", verbose_name="版本单词数"
            ),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="total_words_imported",
            field=models.IntegerField(
                default=0, help_text="该来源导入的总单词数", verbose_name="总导入单词数"
            ),
        ),
        migrations.AddField(
            model_name="vocabularysource",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddIndex(
            model_name="vocabularysource",
            index=models.Index(fields=["name"], name="words_vocab_name_56f6ef_idx"),
        ),
        migrations.AddIndex(
            model_name="vocabularysource",
            index=models.Index(
                fields=["is_active"], name="words_vocab_is_acti_c7fc5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vocabularysource",
            index=models.Index(
                fields=["last_import_at"], name="words_vocab_last_im_2a64f4_idx"
            ),
        ),
    ]
