# Generated by Django 4.2.23 on 2025-08-18 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0006_vocabularysource_auto_create_lists_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phonetic",
                    models.CharField(blank=True, max_length=100, verbose_name="音标"),
                ),
                ("definition", models.TextField(blank=True, verbose_name="释义")),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("名词", "名词"),
                            ("动词", "动词"),
                            ("形容词", "形容词"),
                            ("副词", "副词"),
                            ("代词", "代词"),
                            ("数词", "数词"),
                            ("冠词", "冠词"),
                            ("介词", "介词"),
                            ("连词", "连词"),
                            ("感叹词", "感叹词"),
                            ("缩写词", "缩写词"),
                            ("短语", "短语"),
                            ("句子", "句子"),
                            ("其他", "其他"),
                        ],
                        max_length=50,
                        verbose_name="词性",
                    ),
                ),
                ("example", models.TextField(blank=True, verbose_name="例句")),
                ("note", models.TextField(blank=True, verbose_name="笔记")),
                (
                    "textbook_version",
                    models.CharField(blank=True, max_length=50, verbose_name="教材版本"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "一年级"),
                            ("2", "二年级"),
                            ("3", "三年级"),
                            ("4", "四年级"),
                            ("5", "五年级"),
                            ("6", "六年级"),
                            ("7", "初一"),
                            ("8", "初二"),
                            ("9", "初三"),
                            ("10", "高一"),
                            ("11", "高二"),
                            ("12", "高三"),
                        ],
                        max_length=20,
                        verbose_name="年级",
                    ),
                ),
                (
                    "book_volume",
                    models.CharField(
                        blank=True,
                        help_text="如：三上、三下、四上等",
                        max_length=20,
                        verbose_name="册别",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="如：Unit 1、Unit 2等",
                        max_length=20,
                        verbose_name="单元",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "vocabulary_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_entries",
                        to="words.vocabularylist",
                        verbose_name="词库列表",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="words.word",
                        verbose_name="单词",
                    ),
                ),
            ],
            options={
                "verbose_name": "词条",
                "verbose_name_plural": "词条",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_batch_id",
                    models.CharField(blank=True, max_length=100, verbose_name="导入批次ID"),
                ),
                (
                    "import_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="导入元数据"),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("new", "新增"),
                            ("duplicate", "重复"),
                            ("version", "新版本"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="导入类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "import_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_records",
                        to="words.vocabularysource",
                        verbose_name="导入来源",
                    ),
                ),
                (
                    "word_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_records",
                        to="words.wordentry",
                        verbose_name="词条",
                    ),
                ),
            ],
            options={
                "verbose_name": "导入记录",
                "verbose_name_plural": "导入记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wordentry",
            index=models.Index(fields=["word"], name="words_worde_word_id_aff47f_idx"),
        ),
        migrations.AddIndex(
            model_name="wordentry",
            index=models.Index(
                fields=["vocabulary_list"], name="words_worde_vocabul_ce6d05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordentry",
            index=models.Index(
                fields=["textbook_version", "grade", "book_volume", "unit"],
                name="words_worde_textboo_11c282_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wordentry",
            unique_together={
                (
                    "word",
                    "textbook_version",
                    "grade",
                    "book_volume",
                    "unit",
                    "phonetic",
                    "definition",
                    "part_of_speech",
                    "note",
                )
            },
        ),
        migrations.AddIndex(
            model_name="importrecord",
            index=models.Index(
                fields=["word_entry"], name="words_impor_word_en_f8f0c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrecord",
            index=models.Index(
                fields=["import_source"], name="words_impor_import__fb8f57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrecord",
            index=models.Index(
                fields=["import_batch_id"], name="words_impor_import__3e52b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrecord",
            index=models.Index(
                fields=["import_type"], name="words_impor_import__444931_idx"
            ),
        ),
    ]
