# Generated by Django 4.2.7 on 2025-08-05 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0006_remove_userstreak_user_alter_wordresource_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vocabularysource",
            options={
                "ordering": ["name"],
                "verbose_name": "词库导入来源设置",
                "verbose_name_plural": "词库导入来源设置",
            },
        ),
        migrations.AlterModelOptions(
            name="wordgradelevel",
            options={
                "ordering": ["grader", "level"],
                "verbose_name": "单词分级等级设置",
                "verbose_name_plural": "单词分级等级设置",
            },
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_user_id_b84db4_idx",
        ),
        migrations.RemoveField(
            model_name="word",
            name="is_learned",
        ),
        migrations.RemoveField(
            model_name="word",
            name="user",
        ),
    ]
