# Generated by Django 4.2.7 on 2025-08-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_alter_vocabularysource_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='word',
            name='words_word_has_con_613e5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='word',
            name='words_word_is_vari_ca4ae4_idx',
        ),
        migrations.RemoveField(
            model_name='word',
            name='conflict_data',
        ),
        migrations.RemoveField(
            model_name='word',
            name='conflict_resolved',
        ),
        migrations.RemoveField(
            model_name='word',
            name='has_conflict',
        ),
        migrations.RemoveField(
            model_name='word',
            name='is_variant',
        ),
        migrations.AddField(
            model_name='word',
            name='has_multiple_versions',
            field=models.BooleanField(default=False, help_text='该单词是否有多个版本', verbose_name='是否含有多版本'),
        ),
        migrations.AddField(
            model_name='word',
            name='version_data',
            field=models.JSONField(blank=True, default=dict, help_text='存储版本相关的元数据', verbose_name='版本数据'),
        ),
        migrations.AddField(
            model_name='word',
            name='version_number',
            field=models.IntegerField(default=1, help_text='单词的版本号，从1开始', verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='word',
            name='parent_word',
            field=models.ForeignKey(blank=True, help_text='指向主单词，如果为空则表示这是主单词', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='words.word', verbose_name='主单词'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['has_multiple_versions'], name='words_word_has_mul_2b3668_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['version_number'], name='words_word_version_ab1125_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['parent_word'], name='words_word_parent__b2ea82_idx'),
        ),
    ]
