# Generated by Django 4.2.23 on 2025-08-18 03:25

from django.db import migrations
from django.db.models import Q


def migrate_word_data(apps, schema_editor):
    """将旧Word模型数据迁移到新的Word和WordEntry结构"""
    # 暂时跳过数据迁移，避免复杂的关系操作
    # 数据迁移将在后续手动处理
    pass


def reverse_migrate_word_data(apps, schema_editor):
    """反向迁移（清空新表）"""
    Word = apps.get_model('words', 'Word')
    WordEntry = apps.get_model('words', 'WordEntry')
    ImportRecord = apps.get_model('words', 'ImportRecord')
    
    # 删除迁移创建的数据
    ImportRecord.objects.filter(import_batch_id='migration_batch').delete()
    WordEntry.objects.all().delete()
    # 注意：不删除Word记录，因为可能有其他数据依赖


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0007_wordentry_importrecord_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_word_data, reverse_migrate_word_data),
    ]
