# Generated by Django 4.2.7 on 2025-08-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_remove_word_words_word_has_con_613e5b_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConflictResolution',
        ),
    ]
