# Generated by Django 4.2.23 on 2025-08-18 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0008_auto_20250818_1125"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_vocabul_1742cb_idx",
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_has_mul_2b3668_idx",
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_version_ab1125_idx",
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_parent__b2ea82_idx",
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_import__01e6be_idx",
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_import__fcebf2_idx",
        ),
        migrations.RemoveIndex(
            model_name="word",
            name="words_word_word_2e8399_idx",
        ),
        migrations.RemoveField(
            model_name="word",
            name="book_volume",
        ),
        migrations.RemoveField(
            model_name="word",
            name="definition",
        ),
        migrations.RemoveField(
            model_name="word",
            name="example",
        ),
        migrations.RemoveField(
            model_name="word",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="word",
            name="has_multiple_versions",
        ),
        migrations.RemoveField(
            model_name="word",
            name="import_batch_id",
        ),
        migrations.RemoveField(
            model_name="word",
            name="import_metadata",
        ),
        migrations.RemoveField(
            model_name="word",
            name="import_source",
        ),
        migrations.RemoveField(
            model_name="word",
            name="note",
        ),
        migrations.RemoveField(
            model_name="word",
            name="parent_word",
        ),
        migrations.RemoveField(
            model_name="word",
            name="part_of_speech",
        ),
        migrations.RemoveField(
            model_name="word",
            name="phonetic",
        ),
        migrations.RemoveField(
            model_name="word",
            name="textbook_version",
        ),
        migrations.RemoveField(
            model_name="word",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="word",
            name="version_data",
        ),
        migrations.RemoveField(
            model_name="word",
            name="version_number",
        ),
        migrations.RemoveField(
            model_name="word",
            name="vocabulary_list",
        ),
    ]
