# Generated by Django 4.2.7 on 2025-08-05 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="原始内容")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="articles/", verbose_name="配图"
                    ),
                ),
                ("is_parsed", models.BooleanField(default=False, verbose_name="已解析")),
                (
                    "parsed_content",
                    models.JSONField(blank=True, null=True, verbose_name="解析内容"),
                ),
                ("edited_content", models.TextField(blank=True, verbose_name="编辑内容")),
                (
                    "edit_mode",
                    models.CharField(
                        choices=[("source", "源文本编辑"), ("visual", "可视化编辑")],
                        default="source",
                        max_length=10,
                        verbose_name="编辑模式",
                    ),
                ),
                ("html_content", models.TextField(blank=True, verbose_name="HTML内容")),
                (
                    "paragraph_analysis",
                    models.JSONField(blank=True, null=True, verbose_name="段落分析结果"),
                ),
                (
                    "vocabulary_source",
                    models.CharField(
                        default="default", max_length=50, verbose_name="词库来源"
                    ),
                ),
                (
                    "variant_preference",
                    models.CharField(default="us", max_length=20, verbose_name="变体偏好"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, null=True, verbose_name="额外数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParsedParagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="顺序")),
                (
                    "paragraph_type",
                    models.CharField(
                        choices=[
                            ("title", "标题"),
                            ("list_item", "列表项"),
                            ("indented", "缩进文本"),
                            ("normal", "普通段落"),
                            ("quote", "引用"),
                            ("code", "代码块"),
                        ],
                        max_length=20,
                        verbose_name="段落类型",
                    ),
                ),
                ("original_text", models.TextField(verbose_name="原始文本")),
                ("processed_text", models.TextField(verbose_name="处理后文本")),
                (
                    "word_data",
                    models.JSONField(blank=True, null=True, verbose_name="单词数据"),
                ),
                ("html_content", models.TextField(blank=True, verbose_name="HTML内容")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="article_factory.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "解析段落",
                "verbose_name_plural": "解析段落",
                "ordering": ["article", "order"],
            },
        ),
    ]
