# Generated by Django 4.2.7 on 2025-08-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article_factory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="system_vocabulary_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="系统词库ID"
            ),
        ),
    ]
