# Generated by Django 4.2.7 on 2025-08-04 15:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("words", "0005_alter_wordset_name_alter_wordset_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="目标名称")),
                ("description", models.TextField(blank=True, verbose_name="目标描述")),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("vocabulary_list", "词库"),
                            ("word_set", "词集"),
                            ("grade_level", "分级"),
                        ],
                        max_length=20,
                        verbose_name="目标类型",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="是否为当前目标"),
                ),
                ("total_words", models.IntegerField(default=0, verbose_name="总单词数")),
                ("learned_words", models.IntegerField(default=0, verbose_name="已学单词数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="words.wordgradelevel",
                        verbose_name="分级等级",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "vocabulary_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="words.vocabularylist",
                        verbose_name="词库列表",
                    ),
                ),
                (
                    "word_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="words.wordset",
                        verbose_name="词集",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习目标",
                "verbose_name_plural": "学习目标",
                "ordering": ["-is_current", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="计划名称")),
                (
                    "plan_mode",
                    models.CharField(
                        choices=[
                            ("mechanical", "机械模式"),
                            ("daily_progress", "日进模式"),
                            ("workday", "工作日模式"),
                            ("weekend", "周末模式"),
                        ],
                        max_length=20,
                        verbose_name="计划模式",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=datetime.date.today, verbose_name="开始日期"),
                ),
                ("end_date", models.DateField(verbose_name="结束日期")),
                ("total_words", models.IntegerField(default=0, verbose_name="总单词数")),
                (
                    "daily_target",
                    models.IntegerField(default=0, verbose_name="每日目标单词数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("completed", "已完成"),
                            ("paused", "已暂停"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "learning_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_plans",
                        to="vocabulary_manager.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyStudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_date",
                    models.DateField(default=datetime.date.today, verbose_name="学习日期"),
                ),
                ("target_words", models.IntegerField(default=0, verbose_name="目标单词数")),
                (
                    "completed_words",
                    models.IntegerField(default=0, verbose_name="完成单词数"),
                ),
                (
                    "study_duration",
                    models.DurationField(blank=True, null=True, verbose_name="学习时长"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "learning_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="vocabulary_manager.learningplan",
                        verbose_name="学习计划",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_study_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日学习记录",
                "verbose_name_plural": "每日学习记录",
                "ordering": ["-study_date"],
            },
        ),
        migrations.AddIndex(
            model_name="learningplan",
            index=models.Index(
                fields=["user", "status"], name="vocabulary__user_id_66182a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningplan",
            index=models.Index(
                fields=["learning_goal"], name="vocabulary__learnin_a5cba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningplan",
            index=models.Index(
                fields=["start_date", "end_date"], name="vocabulary__start_d_7c7fa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learninggoal",
            index=models.Index(
                fields=["user", "is_current"], name="vocabulary__user_id_471b4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learninggoal",
            index=models.Index(
                fields=["goal_type"], name="vocabulary__goal_ty_2f96e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailystudyrecord",
            index=models.Index(
                fields=["user", "study_date"], name="vocabulary__user_id_485850_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailystudyrecord",
            index=models.Index(
                fields=["learning_plan", "study_date"],
                name="vocabulary__learnin_929d24_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystudyrecord",
            unique_together={("user", "learning_plan", "study_date")},
        ),
    ]
