# Generated by Django 4.2.7 on 2025-08-04 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vocabulary_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningplan",
            name="plan_mode",
            field=models.CharField(
                choices=[
                    ("mechanical", "机械模式 - 固定每日学习量，不考虑学习进展更新"),
                    ("daily_progress", "日进模式 - 根据学习进展每日更新，按剩余时间均分"),
                    ("workday", "工作日模式 - 只在工作日学习，按剩余工作日均分"),
                    ("weekend", "周末模式 - 只在周末学习，按剩余周末天数均分"),
                ],
                max_length=20,
                verbose_name="计划模式",
            ),
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="当前连续天数"),
                ),
                (
                    "longest_streak",
                    models.IntegerField(default=0, verbose_name="最长连续天数"),
                ),
                (
                    "last_study_date",
                    models.DateField(blank=True, null=True, verbose_name="最后学习日期"),
                ),
                (
                    "total_study_days",
                    models.IntegerField(default=0, verbose_name="总学习天数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户连续学习记录",
                "verbose_name_plural": "用户连续学习记录",
                "indexes": [
                    models.Index(
                        fields=["user"], name="vocabulary__user_id_6a36ee_idx"
                    ),
                    models.Index(
                        fields=["last_study_date"],
                        name="vocabulary__last_st_1addaa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="学习时长"),
                ),
                ("words_studied", models.IntegerField(default=0, verbose_name="学习单词数")),
                ("words_learned", models.IntegerField(default=0, verbose_name="掌握单词数")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习会话",
                "verbose_name_plural": "学习会话",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_time"],
                        name="vocabulary__user_id_f0a232_idx",
                    )
                ],
            },
        ),
    ]
