# Generated by Django 4.2.7 on 2025-08-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "vocabulary_manager",
            "0002_alter_learningplan_plan_mode_userstreak_studysession",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="learning_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_sessions",
                to="vocabulary_manager.learninggoal",
                verbose_name="学习目标",
            ),
        ),
    ]
