# Generated by Django 4.2.7 on 2025-08-05 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0009_remove_conflict_resolution'),
        ('vocabulary_manager', '0003_studysession_learning_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('last_review_date', models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='是否已掌握')),
                ('is_forgotten', models.BooleanField(default=False, verbose_name='是否已遗忘')),
                ('mastered_date', models.DateTimeField(blank=True, null=True, verbose_name='掌握时间')),
                ('first_learned_date', models.DateTimeField(auto_now_add=True, verbose_name='首次学习时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('learning_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to='vocabulary_manager.learninggoal', verbose_name='学习目标')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='words.word', verbose_name='单词')),
            ],
            options={
                'verbose_name': '单词学习进度',
                'verbose_name_plural': '单词学习进度',
                'indexes': [models.Index(fields=['user', 'learning_goal'], name='vocabulary__user_id_06ca7f_idx'), models.Index(fields=['review_count'], name='vocabulary__review__523696_idx'), models.Index(fields=['is_mastered'], name='vocabulary__is_mast_dfb7e5_idx'), models.Index(fields=['is_forgotten'], name='vocabulary__is_forg_2ad2b3_idx')],
                'unique_together': {('user', 'learning_goal', 'word')},
            },
        ),
    ]
