/**
 * 权限常量定义（已迁移到统一权限常量文件）
 * 此文件保留用于向后兼容，所有新代码应使用 unifiedPermissionConstants.js
 * @deprecated 请使用 unifiedPermissionConstants.js 替代
 */

// 从统一权限常量文件导入
import {
  PERMISSION_CATEGORIES as UNIFIED_PERMISSION_CATEGORIES,
  LEARNING_PERMISSIONS as UNIFIED_LEARNING_PERMISSIONS
} from './unifiedPermissionConstants.js'

// 为了向后兼容，重新导出
export const PERMISSION_CATEGORIES = UNIFIED_PERMISSION_CATEGORIES
export const LEARNING_PERMISSIONS = UNIFIED_LEARNING_PERMISSIONS

// 从统一权限常量文件导入其他权限
import {
  CONTENT_PERMISSIONS as UNIFIED_CONTENT_PERMISSIONS,
  SOCIAL_PERMISSIONS as UNIFIED_SOCIAL_PERMISSIONS,
  MANAGEMENT_PERMISSIONS as UNIFIED_MANAGEMENT_PERMISSIONS,
  SYSTEM_PERMISSIONS as UNIFIED_SYSTEM_PERMISSIONS,
  ADVANCED_PERMISSIONS as UNIFIED_ADVANCED_PERMISSIONS,
  ALL_PERMISSIONS as UNIFIED_ALL_PERMISSIONS,
  PERMISSION_CATEGORY_MAP as UNIFIED_PERMISSION_CATEGORY_MAP
} from './unifiedPermissionConstants.js'

// 为了向后兼容，重新导出
export const CONTENT_PERMISSIONS = UNIFIED_CONTENT_PERMISSIONS
export const SOCIAL_PERMISSIONS = UNIFIED_SOCIAL_PERMISSIONS
export const MANAGEMENT_PERMISSIONS = UNIFIED_MANAGEMENT_PERMISSIONS
export const SYSTEM_PERMISSIONS = UNIFIED_SYSTEM_PERMISSIONS
export const ADVANCED_PERMISSIONS = UNIFIED_ADVANCED_PERMISSIONS
export const ALL_PERMISSIONS = UNIFIED_ALL_PERMISSIONS
export const PERMISSION_CATEGORY_MAP = UNIFIED_PERMISSION_CATEGORY_MAP

// 从统一权限常量文件导入显示名称
import {
  PERMISSION_DISPLAY_NAMES as UNIFIED_PERMISSION_DISPLAY_NAMES,
  PERMISSION_CATEGORY_DISPLAY_NAMES as UNIFIED_PERMISSION_CATEGORY_DISPLAY_NAMES
} from './unifiedPermissionConstants.js'

// 为了向后兼容，重新导出
export const PERMISSION_DISPLAY_NAMES = UNIFIED_PERMISSION_DISPLAY_NAMES
export const PERMISSION_CATEGORY_DISPLAY_NAMES = UNIFIED_PERMISSION_CATEGORY_DISPLAY_NAMES

// 导出所有权限常量的集合
export const PERMISSION_CONSTANTS = {
  PERMISSION_CATEGORIES,
  LEARNING_PERMISSIONS,
  CONTENT_PERMISSIONS,
  SOCIAL_PERMISSIONS,
  MANAGEMENT_PERMISSIONS,
  SYSTEM_PERMISSIONS,
  ADVANCED_PERMISSIONS,
  ALL_PERMISSIONS,
  PERMISSION_CATEGORY_MAP,
  PERMISSION_DISPLAY_NAMES,
  PERMISSION_CATEGORY_DISPLAY_NAMES
}