# Generated by Django 4.2.7 on 2025-08-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userengagementmetrics",
            name="peak_activity_hour",
            field=models.IntegerField(blank=True, help_text="活跃高峰时段(0-23)", null=True),
        ),
    ]
