# Generated by Django 4.2.7 on 2025-08-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuModuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=50, unique=True, verbose_name="菜单标识"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="菜单名称")),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-circle", max_length=100, verbose_name="图标类名"
                    ),
                ),
                ("url", models.CharField(max_length=200, verbose_name="菜单链接")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "前台菜单模块",
                "verbose_name_plural": "前台菜单模块管理",
                "ordering": ["sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="PermissionSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("auto", "自动同步"),
                            ("manual", "手动同步"),
                            ("batch", "批量同步"),
                        ],
                        max_length=20,
                        verbose_name="同步类型",
                    ),
                ),
                ("target_type", models.CharField(max_length=50, verbose_name="目标类型")),
                ("target_id", models.CharField(max_length=100, verbose_name="目标ID")),
                ("action", models.CharField(max_length=200, verbose_name="操作")),
                ("result", models.TextField(verbose_name="结果")),
                ("success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "权限同步日志",
                "verbose_name_plural": "权限同步日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleGroupMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("teacher", "教师"),
                            ("student", "学生"),
                            ("parent", "家长"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="角色",
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True, help_text="用户角色变更时自动分配到对应组", verbose_name="自动同步"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Django组",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色组映射",
                "verbose_name_plural": "角色组映射配置",
            },
        ),
        migrations.CreateModel(
            name="RoleMenuPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("teacher", "教师"),
                            ("student", "学生"),
                            ("parent", "家长"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("can_access", models.BooleanField(default=True, verbose_name="可访问")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.menumoduleconfig",
                        verbose_name="菜单模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色菜单权限",
                "verbose_name_plural": "角色菜单权限配置",
                "unique_together": {("role", "menu_module")},
            },
        ),
    ]
