# Generated by Django 4.2.7 on 2025-08-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menumoduleconfig",
            name="menu_level",
            field=models.CharField(
                choices=[("root", "根目录"), ("level1", "一级目录"), ("level2", "二级目录")],
                default="root",
                max_length=10,
                verbose_name="菜单级别",
            ),
        ),
    ]
