# Generated by Django optimization

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    权限系统角色优化索引迁移
    为权限相关的角色字段添加数据库索引以提升查询性能
    """
    
    dependencies = [
        ('permissions', '0001_initial'),
    ]
    
    operations = [
        # RoleMenuPermission索引优化
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolemenupermission_role ON permissions_rolemenupermission(role);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolemenupermission_role;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolemenupermission_role_access ON permissions_rolemenupermission(role, can_access);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolemenupermission_role_access;"
        ),
        
        # RoleGroupMapping索引优化
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolegroupmapping_role ON permissions_rolegroupmapping(role);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolegroupmapping_role;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolegroupmapping_role_sync ON permissions_rolegroupmapping(role, auto_sync);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolegroupmapping_role_sync;"
        ),
        
        # RoleManagement索引优化（如果存在）
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolemanagement_role ON permissions_rolemanagement(role);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolemanagement_role;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolemanagement_active ON permissions_rolemanagement(is_active) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS idx_rolemanagement_active;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolemanagement_role_active ON permissions_rolemanagement(role, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolemanagement_role_active;"
        ),
        
        # MenuModuleConfig索引优化
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_menumoduleconfig_level_active ON permissions_menumoduleconfig(menu_level, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_menumoduleconfig_level_active;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_menumoduleconfig_sort ON permissions_menumoduleconfig(sort_order);",
            reverse_sql="DROP INDEX IF EXISTS idx_menumoduleconfig_sort;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_menumoduleconfig_key ON permissions_menumoduleconfig(key) WHERE key IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_menumoduleconfig_key;"
        ),
        
        # PermissionSyncLog索引优化（如果存在）
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_permissionsynclog_type_target ON permissions_permissionsynclog(sync_type, target_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_permissionsynclog_type_target;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_permissionsynclog_created ON permissions_permissionsynclog(created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_permissionsynclog_created;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_permissionsynclog_success ON permissions_permissionsynclog(success);",
            reverse_sql="DROP INDEX IF EXISTS idx_permissionsynclog_success;"
        ),
        
        # 组合索引用于常见查询
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolemenupermission_menu_role ON permissions_rolemenupermission(menu_module_id, role);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolemenupermission_menu_role;"
        ),
        
        # 日期相关索引
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolemenupermission_created ON permissions_rolemenupermission(created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolemenupermission_created;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_rolegroupmapping_created ON permissions_rolegroupmapping(created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_rolegroupmapping_created;"
        ),
    ]