# Generated by Django 4.2.7 on 2025-08-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menumoduleconfig",
            name="menu_level",
            field=models.CharField(
                choices=[("root", "根目录"), ("level1", "一级目录"), ("level2", "二级目录")],
                default="root",
                max_length=10,
                verbose_name="菜单级别",
            ),
        ),
        migrations.AlterField(
            model_name="rolegroupmapping",
            name="role",
            field=models.CharField(
                help_text="角色标识符，支持自定义角色名称",
                max_length=50,
                unique=True,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="rolemenupermission",
            name="role",
            field=models.CharField(
                help_text="支持预定义和自定义角色", max_length=50, verbose_name="角色"
            ),
        ),
        migrations.CreateModel(
            name="RoleManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="角色标识符，支持自定义角色名称",
                        max_length=50,
                        unique=True,
                        verbose_name="角色",
                    ),
                ),
                ("display_name", models.CharField(max_length=50, verbose_name="显示名称")),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="角色继承关系，子角色自动继承父角色权限",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.rolemanagement",
                        verbose_name="父角色",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="auth.permission", verbose_name="直接权限"
                    ),
                ),
            ],
            options={
                "verbose_name": "角色管理",
                "verbose_name_plural": "角色管理",
                "ordering": ["sort_order", "role"],
            },
        ),
    ]
