# Generated by Django 4.2.23 on 2025-08-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0003_autosyncconfig_optimizedrolegroupmapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="数据模型表名", max_length=64, verbose_name="表名"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="模型表字段名", max_length=64, verbose_name="字段名"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="字段的显示名称", max_length=64, verbose_name="字段显示名"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        default="text",
                        help_text="字段数据类型",
                        max_length=32,
                        verbose_name="字段类型",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="字段是否必填", verbose_name="是否必填"
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False, help_text="是否为敏感字段", verbose_name="是否敏感"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="字段显示排序", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="关联的菜单模块",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.menumoduleconfig",
                        verbose_name="菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单字段表",
                "verbose_name_plural": "菜单字段表",
                "ordering": ["sort_order", "field_name"],
                "unique_together": {("menu", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="FieldPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="角色标识", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "is_query",
                    models.BooleanField(
                        default=True, help_text="是否可查询此字段", verbose_name="可查询"
                    ),
                ),
                (
                    "is_create",
                    models.BooleanField(
                        default=True, help_text="是否可在创建时设置此字段", verbose_name="可创建"
                    ),
                ),
                (
                    "is_update",
                    models.BooleanField(
                        default=True, help_text="是否可更新此字段", verbose_name="可更新"
                    ),
                ),
                (
                    "is_export",
                    models.BooleanField(
                        default=True, help_text="是否可导出此字段", verbose_name="可导出"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="关联的菜单字段",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permissions",
                        to="permissions.menufield",
                        verbose_name="字段",
                    ),
                ),
            ],
            options={
                "verbose_name": "字段权限表",
                "verbose_name_plural": "字段权限表",
                "ordering": ["role", "field"],
                "unique_together": {("role", "field")},
            },
        ),
    ]
