# Generated by Django 4.2.7 on 2025-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("permissions", "0003_update_menu_levels_and_icons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolegroupmapping",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                ],
                max_length=20,
                unique=True,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="rolemenupermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                ],
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.CreateModel(
            name="RoleManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("parent", "家长"),
                            ("teacher", "自由老师"),
                            ("admin", "管理员"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="角色",
                    ),
                ),
                ("display_name", models.CharField(max_length=50, verbose_name="显示名称")),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="auth.permission", verbose_name="权限"
                    ),
                ),
            ],
            options={
                "verbose_name": "角色管理",
                "verbose_name_plural": "角色管理",
                "ordering": ["sort_order", "role"],
            },
        ),
    ]
