# Generated by Django 4.2.7 on 2025-08-07 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("permissions", "0004_alter_rolegroupmapping_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolemanagement",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="角色继承关系，子角色自动继承父角色权限",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.rolemanagement",
                verbose_name="父角色",
            ),
        ),
        migrations.AlterField(
            model_name="rolemanagement",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, to="auth.permission", verbose_name="直接权限"
            ),
        ),
    ]
