# Generated by Django 4.2.23 on 2025-08-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0004_menufield_fieldpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="按钮显示名称", max_length=64, verbose_name="按钮名称"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="权限标识值", max_length=64, verbose_name="权限值"
                    ),
                ),
                (
                    "api",
                    models.CharField(
                        help_text="对应的API接口地址", max_length=200, verbose_name="接口地址"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        default="GET",
                        help_text="API请求方法",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="按钮图标", max_length=64, verbose_name="图标"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="按钮显示排序", verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="按钮是否激活", verbose_name="是否激活"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="关联的菜单模块",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_buttons",
                        to="permissions.menumoduleconfig",
                        verbose_name="关联菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单按钮表",
                "verbose_name_plural": "菜单按钮表",
                "ordering": ["sort_order", "name"],
                "unique_together": {("menu", "value")},
            },
        ),
        migrations.CreateModel(
            name="RoleMenuButtonPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="角色标识", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "data_range",
                    models.IntegerField(
                        choices=[
                            (0, "仅本人数据权限"),
                            (1, "本部门及以下数据权限"),
                            (2, "本部门数据权限"),
                            (3, "全部数据权限"),
                            (4, "自定义数据权限"),
                        ],
                        default=0,
                        help_text="数据权限范围控制",
                        verbose_name="数据权限范围",
                    ),
                ),
                (
                    "custom_dept_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="自定义数据权限关联的部门ID列表",
                        verbose_name="自定义部门权限",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu_button",
                    models.ForeignKey(
                        help_text="关联的菜单按钮",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="button_permissions",
                        to="permissions.menubutton",
                        verbose_name="关联按钮",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色按钮权限表",
                "verbose_name_plural": "角色按钮权限表",
                "ordering": ["role", "menu_button"],
                "unique_together": {("role", "menu_button")},
            },
        ),
    ]
