# Generated by Django 4.2.23 on 2025-08-22 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("permissions", "0005_menubutton_rolemenubuttonpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="部门名称", max_length=100, verbose_name="部门名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="部门唯一编码",
                        max_length=50,
                        unique=True,
                        verbose_name="部门编码",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="部门职能描述", verbose_name="部门描述"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="部门是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="部门显示排序", verbose_name="排序"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="部门联系电话",
                        max_length=20,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="部门邮箱", max_length=254, verbose_name="邮箱"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="部门地址", verbose_name="地址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        help_text="部门负责人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="部门负责人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="上级部门，支持多级部门结构",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="permissions.department",
                        verbose_name="上级部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门管理",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="用户的主要部门", verbose_name="是否主部门"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="在该部门的职位",
                        max_length=100,
                        verbose_name="职位",
                    ),
                ),
                (
                    "join_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="加入部门的日期",
                        verbose_name="加入日期",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="关联是否有效", verbose_name="是否有效"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_users",
                        to="permissions.department",
                        verbose_name="部门",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户部门关联",
                "verbose_name_plural": "用户部门关联",
                "ordering": ["-is_primary", "department__sort_order"],
                "unique_together": {("user", "department")},
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["parent"], name="permissions_parent__cee31f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="permissions_code_203d48_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active"], name="permissions_is_acti_8357d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["sort_order"], name="permissions_sort_or_022c56_idx"
            ),
        ),
    ]
