# Generated by Django 4.2.7 on 2025-08-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0005_rolemanagement_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolemanagement",
            name="role",
            field=models.CharField(
                help_text="角色标识符，支持自定义角色名称",
                max_length=50,
                unique=True,
                verbose_name="角色",
            ),
        ),
    ]
