# Generated by Django 4.2.23 on 2025-08-22 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("permissions", "0006_department_userdepartment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_modular",
                    models.CharField(
                        blank=True,
                        help_text="请求模块",
                        max_length=64,
                        null=True,
                        verbose_name="请求模块",
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        help_text="请求地址",
                        max_length=400,
                        null=True,
                        verbose_name="请求地址",
                    ),
                ),
                (
                    "request_body",
                    models.TextField(
                        blank=True, help_text="请求参数", null=True, verbose_name="请求参数"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        help_text="请求方式",
                        max_length=8,
                        null=True,
                        verbose_name="请求方式",
                    ),
                ),
                (
                    "request_msg",
                    models.TextField(
                        blank=True, help_text="操作说明", null=True, verbose_name="操作说明"
                    ),
                ),
                (
                    "request_ip",
                    models.CharField(
                        blank=True,
                        help_text="请求IP地址",
                        max_length=32,
                        null=True,
                        verbose_name="请求IP地址",
                    ),
                ),
                (
                    "request_browser",
                    models.CharField(
                        blank=True,
                        help_text="请求浏览器",
                        max_length=64,
                        null=True,
                        verbose_name="请求浏览器",
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        blank=True,
                        help_text="响应状态码",
                        max_length=32,
                        null=True,
                        verbose_name="响应状态码",
                    ),
                ),
                (
                    "request_os",
                    models.CharField(
                        blank=True,
                        help_text="操作系统",
                        max_length=64,
                        null=True,
                        verbose_name="操作系统",
                    ),
                ),
                (
                    "json_result",
                    models.TextField(
                        blank=True, help_text="返回信息", null=True, verbose_name="返回信息"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, help_text="响应状态", verbose_name="响应状态"
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, help_text="操作发生时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="执行操作的用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "system_operation_log",
                "ordering": ["-create_datetime"],
                "indexes": [
                    models.Index(
                        fields=["create_datetime"],
                        name="system_oper_create__1a8f25_idx",
                    ),
                    models.Index(
                        fields=["creator", "create_datetime"],
                        name="system_oper_creator_b472c5_idx",
                    ),
                    models.Index(
                        fields=["request_method", "create_datetime"],
                        name="system_oper_request_f9fc66_idx",
                    ),
                    models.Index(
                        fields=["status", "create_datetime"],
                        name="system_oper_status_b2b0df_idx",
                    ),
                ],
            },
        ),
    ]
