# Generated by Django 4.2.7 on 2025-08-08 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0002_role_optimization_indexes"),
        ("permissions", "0007_alter_rolegroupmapping_role"),
    ]

    operations = []
