# Generated by Django 4.2.23 on 2025-08-24 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0007_operationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="默认配置", max_length=100, verbose_name="配置名称"
                    ),
                ),
                (
                    "slot_count",
                    models.IntegerField(
                        choices=[(4, "4个槽位"), (5, "5个槽位")],
                        default=4,
                        help_text="前端底部导航菜单的槽位数量，仅允许4或5个",
                        verbose_name="槽位数量",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="是否为当前生效的配置", verbose_name="是否启用"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="配置说明", verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "槽位配置",
                "verbose_name_plural": "槽位配置管理",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="rolemenupermission",
            options={
                "verbose_name": "角色菜单权限(已废弃)",
                "verbose_name_plural": "角色菜单权限配置(已废弃)",
            },
        ),
        migrations.CreateModel(
            name="RoleMenuAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="支持预定义和自定义角色", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "slot_position",
                    models.IntegerField(
                        help_text="在底部导航中的位置（1-5），超出最大槽位数时自动设为无效", verbose_name="槽位位置"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, help_text="当槽位位置超出最大值时自动设为无效", verbose_name="是否有效"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu_module",
                    models.ForeignKey(
                        help_text="只能分配根级别的菜单",
                        limit_choices_to={"menu_level": "root"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.menumoduleconfig",
                        verbose_name="菜单模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色菜单分配",
                "verbose_name_plural": "角色菜单分配管理",
                "ordering": ["role", "slot_position"],
                "unique_together": {("role", "menu_module")},
            },
        ),
        migrations.CreateModel(
            name="MenuValidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="支持预定义和自定义角色", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, help_text="该菜单对该角色是否有效", verbose_name="是否有效"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.menumoduleconfig",
                        verbose_name="菜单模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单有效性",
                "verbose_name_plural": "菜单有效性配置",
                "ordering": [
                    "role",
                    "menu_module__menu_level",
                    "menu_module__sort_order",
                ],
                "unique_together": {("role", "menu_module")},
            },
        ),
    ]
