# Generated by Django 4.2.7 on 2025-08-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0008_merge_20250808_2024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolemenupermission",
            name="role",
            field=models.CharField(
                help_text="支持预定义和自定义角色", max_length=50, verbose_name="角色"
            ),
        ),
    ]
