# Generated by Django migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_slotconfig_alter_rolemenupermission_options_and_more'),
    ]

    operations = [
        # 删除 RoleMenuPermission 模型
        migrations.DeleteModel(
            name='RoleMenuPermission',
        ),
    ]