# Generated by Django 4.2.23 on 2025-08-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0009_remove_rolemenupermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slotconfig",
            options={
                "ordering": ["-is_active", "role", "-created_at"],
                "verbose_name": "槽位配置",
                "verbose_name_plural": "槽位配置管理",
            },
        ),
        migrations.AddField(
            model_name="slotconfig",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="角色标识，不同角色可以有不同的槽位配置",
                max_length=50,
                null=True,
                verbose_name="角色",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slotconfig",
            unique_together={("role",)},
        ),
    ]
