# Generated by Django 4.2.23 on 2025-08-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0010_alter_slotconfig_options_slotconfig_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontendMenuConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="前台显示的菜单名称", max_length=100, verbose_name="菜单名称"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="菜单唯一标识符",
                        max_length=50,
                        unique=True,
                        verbose_name="菜单标识",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="菜单图标类名或图标路径",
                        max_length=100,
                        verbose_name="图标",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="菜单跳转链接", max_length=200, verbose_name="链接地址"
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("navigation", "导航菜单"),
                            ("sidebar", "侧边栏菜单"),
                            ("dropdown", "下拉菜单"),
                            ("tab", "标签页菜单"),
                        ],
                        default="navigation",
                        max_length=20,
                        verbose_name="菜单类型",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header", "顶部"),
                            ("sidebar", "侧边栏"),
                            ("footer", "底部"),
                            ("floating", "浮动"),
                        ],
                        default="header",
                        max_length=20,
                        verbose_name="显示位置",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="菜单显示顺序，数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="菜单是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "is_external",
                    models.BooleanField(
                        default=False, help_text="是否为外部链接", verbose_name="外部链接"
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        default="_self",
                        help_text="链接打开方式：_self(当前窗口)、_blank(新窗口)",
                        max_length=20,
                        verbose_name="打开方式",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="菜单功能描述", verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="上级菜单，支持多级菜单结构",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.frontendmenuconfig",
                        verbose_name="父菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "前台菜单配置",
                "verbose_name_plural": "前台菜单配置管理",
                "ordering": ["position", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FrontendMenuRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="角色标识符，支持预定义和自定义角色", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="该角色对此菜单的访问权限是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text="为特定角色自定义的菜单显示名称，留空则使用默认名称",
                        max_length=100,
                        verbose_name="自定义名称",
                    ),
                ),
                (
                    "custom_icon",
                    models.CharField(
                        blank=True,
                        help_text="为特定角色自定义的菜单图标，留空则使用默认图标",
                        max_length=100,
                        verbose_name="自定义图标",
                    ),
                ),
                (
                    "sort_order_override",
                    models.IntegerField(
                        blank=True,
                        help_text="为特定角色自定义的排序，留空则使用菜单默认排序",
                        null=True,
                        verbose_name="排序覆盖",
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(
                        default=True, help_text="是否可以查看此菜单", verbose_name="可查看"
                    ),
                ),
                (
                    "can_access",
                    models.BooleanField(
                        default=True, help_text="是否可以访问此菜单链接", verbose_name="可访问"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="权限生效时间，留空表示立即生效",
                        null=True,
                        verbose_name="生效时间",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="权限失效时间，留空表示永久有效",
                        null=True,
                        verbose_name="失效时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="关联的前台菜单",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="permissions.frontendmenuconfig",
                        verbose_name="菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "前台菜单角色分配",
                "verbose_name_plural": "前台菜单角色分配管理",
                "ordering": ["menu__position", "menu__sort_order", "role"],
                "indexes": [
                    models.Index(
                        fields=["role", "is_active"], name="permissions_role_d80bfd_idx"
                    ),
                    models.Index(
                        fields=["menu", "role"], name="permissions_menu_id_287a21_idx"
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="permissions_valid_f_f65ae0_idx",
                    ),
                ],
                "unique_together": {("menu", "role")},
            },
        ),
        migrations.AddIndex(
            model_name="frontendmenuconfig",
            index=models.Index(
                fields=["position", "sort_order"], name="permissions_positio_89ae7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frontendmenuconfig",
            index=models.Index(
                fields=["is_active"], name="permissions_is_acti_84808b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frontendmenuconfig",
            index=models.Index(
                fields=["parent"], name="permissions_parent__fa0271_idx"
            ),
        ),
    ]
