# Generated by Django 4.2.23 on 2025-08-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("permissions", "0011_frontendmenuconfig_frontendmenuroleassignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupRoleIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("role_linked", "已关联角色"),
                            ("orphaned", "孤立组"),
                            ("system", "系统组"),
                            ("manual", "手动创建"),
                        ],
                        default="manual",
                        help_text="组的角色关联状态",
                        max_length=20,
                        verbose_name="组状态",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "已同步"),
                            ("pending", "待同步"),
                            ("failed", "同步失败"),
                            ("disabled", "已禁用"),
                        ],
                        default="synced",
                        help_text="与角色系统的同步状态",
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "role_identifier",
                    models.CharField(
                        blank=True,
                        help_text="关联的角色标识符，为空表示未关联角色",
                        max_length=50,
                        null=True,
                        verbose_name="关联角色标识",
                    ),
                ),
                (
                    "display_prefix",
                    models.CharField(
                        default="[ROLE]",
                        help_text="在管理界面显示的前缀标识",
                        max_length=20,
                        verbose_name="显示前缀",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="最后一次同步的时间",
                        null=True,
                        verbose_name="最后同步时间",
                    ),
                ),
                (
                    "sync_error_message",
                    models.TextField(
                        blank=True, help_text="同步失败时的错误信息", verbose_name="同步错误信息"
                    ),
                ),
                (
                    "is_auto_managed",
                    models.BooleanField(
                        default=True, help_text="是否由系统自动管理此组", verbose_name="自动管理"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Django组角色标识",
                "verbose_name_plural": "Django组角色标识管理",
                "ordering": ["status", "group__name"],
            },
        ),
        migrations.CreateModel(
            name="RoleMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        help_text="UserRole中定义的角色标识符",
                        max_length=50,
                        unique=True,
                        verbose_name="用户角色",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="映射关系是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True, help_text="是否自动同步权限变更", verbose_name="自动同步"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="映射关系说明", verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色映射",
                "verbose_name_plural": "角色映射管理",
                "ordering": ["user_role"],
            },
        ),
        migrations.AlterModelOptions(
            name="rolegroupmapping",
            options={
                "ordering": ["-priority", "role"],
                "verbose_name": "角色组映射",
                "verbose_name_plural": "角色组映射配置",
            },
        ),
        migrations.AddField(
            model_name="rolegroupmapping",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="映射是否启用", verbose_name="是否启用"
            ),
        ),
        migrations.AddField(
            model_name="rolegroupmapping",
            name="priority",
            field=models.IntegerField(
                default=0, help_text="同步优先级，数字越大优先级越高", verbose_name="优先级"
            ),
        ),
        migrations.AddIndex(
            model_name="rolegroupmapping",
            index=models.Index(fields=["role"], name="permissions_role_f4fc07_idx"),
        ),
        migrations.AddIndex(
            model_name="rolegroupmapping",
            index=models.Index(
                fields=["is_active"], name="permissions_is_acti_6a73f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolegroupmapping",
            index=models.Index(
                fields=["priority"], name="permissions_priorit_bc7f1a_idx"
            ),
        ),
        migrations.AddField(
            model_name="rolemapping",
            name="role_management",
            field=models.ForeignKey(
                help_text="对应的RoleManagement实例",
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.rolemanagement",
                verbose_name="角色管理",
            ),
        ),
        migrations.AddField(
            model_name="grouproleidentifier",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_identifier",
                to="auth.group",
                verbose_name="Django组",
            ),
        ),
        migrations.AddIndex(
            model_name="rolemapping",
            index=models.Index(
                fields=["user_role"], name="permissions_user_ro_62e9d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolemapping",
            index=models.Index(
                fields=["is_active"], name="permissions_is_acti_0d466a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grouproleidentifier",
            index=models.Index(fields=["status"], name="permissions_status_60096c_idx"),
        ),
        migrations.AddIndex(
            model_name="grouproleidentifier",
            index=models.Index(
                fields=["sync_status"], name="permissions_sync_st_87cb55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grouproleidentifier",
            index=models.Index(
                fields=["role_identifier"], name="permissions_role_id_8a6133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grouproleidentifier",
            index=models.Index(
                fields=["is_auto_managed"], name="permissions_is_auto_7a0c58_idx"
            ),
        ),
    ]
