# Generated by Django 4.2.23 on 2025-08-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0012_grouproleidentifier_rolemapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menumoduleconfig",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="上级菜单，支持多级菜单结构",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.menumoduleconfig",
                verbose_name="父菜单",
            ),
        ),
        migrations.AlterField(
            model_name="optimizedrolegroupmapping",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("parent", "家长"),
                    ("teacher", "自由老师"),
                    ("admin", "管理员"),
                    ("dean", "教导主任"),
                    ("academic_director", "教务主任"),
                    ("research_leader", "教研组长"),
                    ("project_assistant", "项目助理"),
                    ("project_manager_assistant", "项目管理助理"),
                ],
                help_text="角色类型",
                max_length=50,
                unique=True,
            ),
        ),
    ]
