# Generated by Django 4.2.23 on 2025-08-27 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0013_add_parent_to_menumoduleconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menumoduleconfig",
            name="parent",
        ),
        migrations.AlterUniqueTogether(
            name="slotconfig",
            unique_together={("role", "slot_count")},
        ),
    ]
