# Generated by Django 4.2.23 on 2025-08-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0014_remove_menumoduleconfig_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleSlotLevel1MenuAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="该一级菜单是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="一级菜单的排序", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "level1_menu",
                    models.ForeignKey(
                        help_text="分配的一级菜单",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.frontendmenuconfig",
                        verbose_name="一级菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色槽位一级菜单分配",
                "verbose_name_plural": "角色槽位一级菜单分配管理",
                "ordering": ["role_slot_assignment", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="RoleSlotMenuAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="角色标识符，支持预定义和自定义角色", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "slot_position",
                    models.IntegerField(
                        help_text="在底部导航中的位置（1-5），根据角色槽位配置确定", verbose_name="槽位位置"
                    ),
                ),
                (
                    "menu_status",
                    models.CharField(
                        choices=[
                            ("active", "当前激活"),
                            ("backup", "候补菜单"),
                            ("disabled", "已禁用"),
                        ],
                        default="active",
                        help_text="菜单的激活状态：当前激活、候补菜单或已禁用",
                        max_length=20,
                        verbose_name="菜单状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="该槽位分配是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="同一槽位内的排序", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "root_menu",
                    models.ForeignKey(
                        help_text="分配的根级菜单",
                        limit_choices_to={"parent__isnull": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.frontendmenuconfig",
                        verbose_name="根菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色槽位菜单分配",
                "verbose_name_plural": "角色槽位菜单分配管理",
                "ordering": ["role", "slot_position", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="RoleSlotLevel2MenuAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="该二级菜单是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="二级菜单的排序", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "level1_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level2_assignments",
                        to="permissions.roleslotlevel1menuassignment",
                        verbose_name="一级菜单分配",
                    ),
                ),
                (
                    "level2_menu",
                    models.ForeignKey(
                        help_text="分配的二级菜单",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.frontendmenuconfig",
                        verbose_name="二级菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色槽位二级菜单分配",
                "verbose_name_plural": "角色槽位二级菜单分配管理",
                "ordering": ["level1_assignment", "sort_order"],
            },
        ),
        migrations.AddField(
            model_name="roleslotlevel1menuassignment",
            name="role_slot_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="level1_assignments",
                to="permissions.roleslotmenuassignment",
                verbose_name="槽位分配",
            ),
        ),
        migrations.AddIndex(
            model_name="roleslotmenuassignment",
            index=models.Index(
                fields=["role", "slot_position"], name="permissions_role_6d4e1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleslotmenuassignment",
            index=models.Index(
                fields=["menu_status", "is_active"],
                name="permissions_menu_st_3c8cda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roleslotmenuassignment",
            index=models.Index(
                fields=["role", "is_active"], name="permissions_role_655c6f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roleslotmenuassignment",
            unique_together={("role", "slot_position", "root_menu")},
        ),
        migrations.AlterUniqueTogether(
            name="roleslotlevel2menuassignment",
            unique_together={("level1_assignment", "level2_menu")},
        ),
        migrations.AlterUniqueTogether(
            name="roleslotlevel1menuassignment",
            unique_together={("role_slot_assignment", "level1_menu")},
        ),
    ]
