# Generated by Django 4.2.23 on 2025-08-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "permissions",
            "0015_roleslotlevel1menuassignment_roleslotmenuassignment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("name", models.CharField(max_length=100, verbose_name="菜单名称")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "key",
                    models.CharField(
                        help_text="菜单唯一标识符",
                        max_length=50,
                        unique=True,
                        verbose_name="菜单标识",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="菜单图标类名或图标路径",
                        max_length=100,
                        verbose_name="图标",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="菜单跳转链接",
                        max_length=200,
                        verbose_name="链接地址",
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("navigation", "导航菜单"),
                            ("sidebar", "侧边栏菜单"),
                            ("dropdown", "下拉菜单"),
                            ("tab", "标签页菜单"),
                            ("module", "模块菜单"),
                        ],
                        default="navigation",
                        max_length=20,
                        verbose_name="菜单类型",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header", "顶部"),
                            ("sidebar", "侧边栏"),
                            ("footer", "底部"),
                            ("floating", "浮动"),
                            ("slot", "槽位"),
                        ],
                        default="header",
                        max_length=20,
                        verbose_name="显示位置",
                    ),
                ),
                (
                    "menu_level",
                    models.CharField(
                        choices=[
                            ("root", "根目录"),
                            ("level1", "一级目录"),
                            ("level2", "二级目录"),
                        ],
                        default="root",
                        max_length=10,
                        verbose_name="菜单级别",
                    ),
                ),
                (
                    "is_external",
                    models.BooleanField(
                        default=False, help_text="是否为外部链接", verbose_name="外部链接"
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        default="_self",
                        help_text="链接打开方式：_self(当前窗口)、_blank(新窗口)",
                        max_length=20,
                        verbose_name="打开方式",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="上级菜单，支持多级菜单结构",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.menuconfig",
                        verbose_name="父菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "统一菜单配置",
                "verbose_name_plural": "统一菜单配置管理",
                "ordering": ["position", "sort_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="frontendmenuconfig",
            options={
                "ordering": ["position", "sort_order", "name"],
                "verbose_name": "前台菜单配置(已废弃)",
                "verbose_name_plural": "前台菜单配置管理(已废弃)",
            },
        ),
        migrations.AlterModelOptions(
            name="frontendmenuroleassignment",
            options={
                "ordering": ["menu__position", "menu__sort_order", "role"],
                "verbose_name": "前台菜单角色分配(已废弃)",
                "verbose_name_plural": "前台菜单角色分配管理(已废弃)",
            },
        ),
        migrations.AlterModelOptions(
            name="menumoduleconfig",
            options={
                "ordering": ["sort_order", "key"],
                "verbose_name": "前台菜单模块(已废弃)",
                "verbose_name_plural": "前台菜单模块管理(已废弃)",
            },
        ),
        migrations.AlterModelOptions(
            name="roleslotlevel1menuassignment",
            options={
                "ordering": ["role_slot_assignment", "sort_order"],
                "verbose_name": "角色槽位一级菜单分配(已废弃)",
                "verbose_name_plural": "角色槽位一级菜单分配管理(已废弃)",
            },
        ),
        migrations.AlterModelOptions(
            name="roleslotlevel2menuassignment",
            options={
                "ordering": ["level1_assignment", "sort_order"],
                "verbose_name": "角色槽位二级菜单分配(已废弃)",
                "verbose_name_plural": "角色槽位二级菜单分配管理(已废弃)",
            },
        ),
        migrations.AlterModelOptions(
            name="roleslotmenuassignment",
            options={
                "ordering": ["role", "slot_position", "sort_order"],
                "verbose_name": "角色槽位菜单分配(已废弃)",
                "verbose_name_plural": "角色槽位菜单分配管理(已废弃)",
            },
        ),
        migrations.RemoveField(
            model_name="slotconfig",
            name="description",
        ),
        migrations.AddField(
            model_name="slotconfig",
            name="slot_position",
            field=models.IntegerField(
                default=1, help_text="在底部导航中的位置（1-5）", verbose_name="槽位位置"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slotconfig",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="role",
            field=models.CharField(
                default=1,
                help_text="角色标识符，支持预定义和自定义角色",
                max_length=50,
                verbose_name="角色",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SlotAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="角色标识符", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "slot_position",
                    models.IntegerField(
                        help_text="在底部导航中的位置（1-5）", verbose_name="槽位位置"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "当前激活"),
                            ("backup", "候补菜单"),
                            ("disabled", "已禁用"),
                        ],
                        default="active",
                        help_text="槽位的激活状态",
                        max_length=20,
                        verbose_name="槽位状态",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="同一槽位内的优先级，数字越大优先级越高", verbose_name="优先级"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="分配到槽位的根菜单",
                        limit_choices_to={"parent__isnull": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.menuconfig",
                        verbose_name="根菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "槽位分配",
                "verbose_name_plural": "槽位分配管理",
                "ordering": ["role", "slot_position", "-priority"],
                "indexes": [
                    models.Index(
                        fields=["role", "slot_position"],
                        name="permissions_role_c31d6e_idx",
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="permissions_status_585679_idx",
                    ),
                    models.Index(
                        fields=["role", "is_active"], name="permissions_role_71df7d_idx"
                    ),
                ],
                "unique_together": {("role", "slot_position", "menu")},
            },
        ),
        migrations.CreateModel(
            name="MenuRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="角色标识符，支持预定义和自定义角色", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="该角色对此菜单的访问权限是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(
                        default=True, help_text="是否可以查看此菜单", verbose_name="可查看"
                    ),
                ),
                (
                    "can_access",
                    models.BooleanField(
                        default=True, help_text="是否可以访问此菜单链接", verbose_name="可访问"
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text="为特定角色自定义的菜单显示名称，留空则使用默认名称",
                        max_length=100,
                        verbose_name="自定义名称",
                    ),
                ),
                (
                    "custom_icon",
                    models.CharField(
                        blank=True,
                        help_text="为特定角色自定义的菜单图标，留空则使用默认图标",
                        max_length=100,
                        verbose_name="自定义图标",
                    ),
                ),
                (
                    "sort_order_override",
                    models.IntegerField(
                        blank=True,
                        help_text="为特定角色自定义的排序，留空则使用菜单默认排序",
                        null=True,
                        verbose_name="排序覆盖",
                    ),
                ),
                (
                    "slot_position",
                    models.IntegerField(
                        blank=True,
                        help_text="在底部导航中的位置（1-5），仅对槽位菜单有效",
                        null=True,
                        verbose_name="槽位位置",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="权限生效时间，留空表示立即生效",
                        null=True,
                        verbose_name="生效时间",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="权限失效时间，留空表示永久有效",
                        null=True,
                        verbose_name="失效时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="关联的菜单",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="permissions.menuconfig",
                        verbose_name="菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单角色分配",
                "verbose_name_plural": "菜单角色分配管理",
                "ordering": ["menu__position", "menu__sort_order", "role"],
                "indexes": [
                    models.Index(
                        fields=["role", "is_active"], name="permissions_role_3a31d0_idx"
                    ),
                    models.Index(
                        fields=["menu", "role"], name="permissions_menu_id_244d14_idx"
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="permissions_valid_f_3f959e_idx",
                    ),
                    models.Index(
                        fields=["slot_position"], name="permissions_slot_po_6801a2_idx"
                    ),
                ],
                "unique_together": {("menu", "role")},
            },
        ),
        migrations.AddIndex(
            model_name="menuconfig",
            index=models.Index(
                fields=["position", "sort_order"], name="permissions_positio_a74bd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuconfig",
            index=models.Index(
                fields=["is_active"], name="permissions_is_acti_ec35cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuconfig",
            index=models.Index(
                fields=["parent"], name="permissions_parent__7a8af7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuconfig",
            index=models.Index(
                fields=["menu_type"], name="permissions_menu_ty_363481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuconfig",
            index=models.Index(
                fields=["menu_level"], name="permissions_menu_le_5885df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuconfig",
            index=models.Index(fields=["key"], name="permissions_key_b9be89_idx"),
        ),
    ]
