# Generated by Django 4.2.23 on 2025-08-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0016_menuconfig_alter_frontendmenuconfig_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="frontendmenuroleassignment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="frontendmenuroleassignment",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="menuconfig",
            name="parent",
        ),
        migrations.AlterUniqueTogether(
            name="menuroleassignment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="menuroleassignment",
            name="menu",
        ),
        migrations.AlterUniqueTogether(
            name="rolemenuassignment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rolemenuassignment",
            name="menu_module",
        ),
        migrations.AlterUniqueTogether(
            name="slotassignment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="slotassignment",
            name="menu",
        ),
        migrations.AlterModelOptions(
            name="menumoduleconfig",
            options={
                "ordering": ["sort_order", "key"],
                "verbose_name": "前台菜单模块",
                "verbose_name_plural": "前台菜单模块管理",
            },
        ),
        migrations.AlterModelOptions(
            name="roleslotlevel1menuassignment",
            options={
                "ordering": ["role_slot_assignment", "sort_order"],
                "verbose_name": "角色槽位一级菜单分配",
                "verbose_name_plural": "角色槽位一级菜单分配管理",
            },
        ),
        migrations.AlterModelOptions(
            name="roleslotlevel2menuassignment",
            options={
                "ordering": ["level1_assignment", "sort_order"],
                "verbose_name": "角色槽位二级菜单分配",
                "verbose_name_plural": "角色槽位二级菜单分配管理",
            },
        ),
        migrations.AlterModelOptions(
            name="roleslotmenuassignment",
            options={
                "ordering": ["role", "slot_position", "sort_order"],
                "verbose_name": "角色槽位菜单分配",
                "verbose_name_plural": "角色槽位菜单分配管理",
            },
        ),
        migrations.RemoveField(
            model_name="slotconfig",
            name="slot_position",
        ),
        migrations.RemoveField(
            model_name="slotconfig",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="slotconfig",
            name="description",
            field=models.TextField(blank=True, help_text="配置说明", verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="roleslotlevel1menuassignment",
            name="level1_menu",
            field=models.ForeignKey(
                help_text="分配的一级菜单",
                limit_choices_to={"menu_level": "level1"},
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.menumoduleconfig",
                verbose_name="一级菜单",
            ),
        ),
        migrations.AlterField(
            model_name="roleslotlevel2menuassignment",
            name="level2_menu",
            field=models.ForeignKey(
                help_text="分配的二级菜单",
                limit_choices_to={"menu_level": "level2"},
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.menumoduleconfig",
                verbose_name="二级菜单",
            ),
        ),
        migrations.AlterField(
            model_name="roleslotmenuassignment",
            name="root_menu",
            field=models.ForeignKey(
                help_text="分配的根级菜单",
                limit_choices_to={"menu_level": "root"},
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.menumoduleconfig",
                verbose_name="根菜单",
            ),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="是否为当前生效的配置", verbose_name="是否启用"
            ),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="角色标识，不同角色可以有不同的槽位配置",
                max_length=50,
                null=True,
                verbose_name="角色",
            ),
        ),
        migrations.DeleteModel(
            name="FrontendMenuConfig",
        ),
        migrations.DeleteModel(
            name="FrontendMenuRoleAssignment",
        ),
        migrations.DeleteModel(
            name="MenuConfig",
        ),
        migrations.DeleteModel(
            name="MenuRoleAssignment",
        ),
        migrations.DeleteModel(
            name="RoleMenuAssignment",
        ),
        migrations.DeleteModel(
            name="SlotAssignment",
        ),
    ]
