# Generated by Django 4.2.23 on 2025-08-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0017_remove_deprecated_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleSlotMenuConfigRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="配置规则的名称", max_length=100, verbose_name="规则名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="详细描述此配置规则的作用和逻辑", verbose_name="规则描述"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("auto_assign", "自动分配"),
                            ("priority_based", "优先级分配"),
                            ("conditional", "条件分配"),
                            ("template_based", "模板分配"),
                        ],
                        default="auto_assign",
                        help_text="配置规则的类型",
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "target_roles",
                    models.TextField(
                        help_text="适用的角色列表，用逗号分隔，支持通配符*", verbose_name="目标角色"
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("slot_count_eq", "槽位数量等于"),
                            ("slot_count_gte", "槽位数量大于等于"),
                            ("slot_count_lte", "槽位数量小于等于"),
                            ("role_match", "角色匹配"),
                            ("role_contains", "角色包含"),
                            ("combined", "组合条件"),
                        ],
                        default="slot_count_eq",
                        help_text="触发条件的类型",
                        max_length=20,
                        verbose_name="条件类型",
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        help_text="条件的具体值，支持数字、字符串或JSON格式的复杂条件",
                        max_length=200,
                        verbose_name="条件值",
                    ),
                ),
                (
                    "menu_assignments",
                    models.TextField(
                        help_text="JSON格式的菜单分配规则，定义如何分配菜单到槽位", verbose_name="菜单分配规则"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="规则执行优先级，数字越大优先级越高", verbose_name="优先级"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="规则是否启用", verbose_name="是否启用"
                    ),
                ),
                (
                    "auto_apply",
                    models.BooleanField(
                        default=False, help_text="是否在条件满足时自动应用此规则", verbose_name="自动应用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色槽位菜单配置规则",
                "verbose_name_plural": "角色槽位菜单配置规则管理",
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "is_active"],
                        name="permissions_rule_ty_bade1b_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_active"],
                        name="permissions_priorit_32c837_idx",
                    ),
                    models.Index(
                        fields=["auto_apply", "is_active"],
                        name="permissions_auto_ap_5c0046_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleSlotMenuConfigHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="应用配置的角色", max_length=50, verbose_name="角色"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("rule_applied", "规则应用"),
                            ("manual_config", "手动配置"),
                            ("auto_sync", "自动同步"),
                            ("rule_reverted", "规则回滚"),
                        ],
                        default="rule_applied",
                        help_text="配置操作的类型",
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "slot_count",
                    models.IntegerField(help_text="应用时的槽位数量", verbose_name="槽位数量"),
                ),
                (
                    "before_config",
                    models.TextField(
                        blank=True, help_text="JSON格式的配置前状态", verbose_name="配置前状态"
                    ),
                ),
                (
                    "after_config",
                    models.TextField(
                        blank=True, help_text="JSON格式的配置后状态", verbose_name="配置后状态"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(
                        default=True, help_text="配置是否成功应用", verbose_name="是否成功"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="配置失败时的错误信息", verbose_name="错误信息"
                    ),
                ),
                (
                    "applied_by",
                    models.CharField(
                        blank=True,
                        help_text="执行配置的用户或系统",
                        max_length=100,
                        verbose_name="操作者",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "config_rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="应用的配置规则",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="permissions.roleslotmenuconfigrule",
                        verbose_name="配置规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色槽位菜单配置历史",
                "verbose_name_plural": "角色槽位菜单配置历史",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["role", "created_at"],
                        name="permissions_role_b4228f_idx",
                    ),
                    models.Index(
                        fields=["config_rule", "created_at"],
                        name="permissions_config__8d1505_idx",
                    ),
                    models.Index(
                        fields=["action_type", "is_success"],
                        name="permissions_action__f03478_idx",
                    ),
                ],
            },
        ),
    ]
