# Generated by Django 4.2.23 on 2025-09-21 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0018_roleslotmenuconfigrule_roleslotmenuconfighistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roleslotlevel1menuassignment",
            options={
                "ordering": ["role_slot_assignment", "sort_order"],
                "verbose_name": "角色槽位一级菜单分配",
                "verbose_name_plural": "角色槽位根菜单和一级菜单分配管理",
            },
        ),
        migrations.DeleteModel(
            name="RoleSlotMenuConfigHistory",
        ),
        migrations.DeleteModel(
            name="RoleSlotMenuConfigRule",
        ),
    ]
