# Generated by Django 4.2.7 on 2025-08-05 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("words", "0006_remove_userstreak_user_alter_wordresource_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="目标名称")),
                ("description", models.TextField(blank=True, verbose_name="目标描述")),
                (
                    "target_words_count",
                    models.IntegerField(default=100, verbose_name="目标单词数量"),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="开始日期"
                    ),
                ),
                ("end_date", models.DateField(verbose_name="结束日期")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习目标",
                "verbose_name_plural": "学习目标",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("words_studied", models.IntegerField(default=0, verbose_name="学习单词数")),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="正确答案数"),
                ),
                ("total_answers", models.IntegerField(default=0, verbose_name="总答案数")),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teaching.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习会话",
                "verbose_name_plural": "学习会话",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="WordLearningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(max_length=200, verbose_name="用户答案")),
                ("is_correct", models.BooleanField(verbose_name="是否正确")),
                ("response_time", models.FloatField(verbose_name="响应时间（秒）")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teaching.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="teaching.learningsession",
                        verbose_name="学习会话",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="words.word",
                        verbose_name="单词",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词学习记录",
                "verbose_name_plural": "单词学习记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("daily", "每日计划"),
                            ("weekly", "每周计划"),
                            ("custom", "自定义计划"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="计划类型",
                    ),
                ),
                (
                    "words_per_day",
                    models.IntegerField(default=10, verbose_name="每日单词数"),
                ),
                (
                    "review_interval",
                    models.IntegerField(default=1, verbose_name="复习间隔（天）"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="teaching.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
            },
        ),
        migrations.CreateModel(
            name="GoalWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_words",
                        to="teaching.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="words.word",
                        verbose_name="单词",
                    ),
                ),
            ],
            options={
                "verbose_name": "目标单词",
                "verbose_name_plural": "目标单词",
                "unique_together": {("goal", "word")},
            },
        ),
    ]
