# Generated by Django 4.2.7 on 2025-08-05 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0006_remove_userstreak_user_alter_wordresource_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teaching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal_associations",
                to="words.word",
                verbose_name="单词",
            ),
        ),
        migrations.AlterField(
            model_name="learningsession",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="teaching.learninggoal",
                verbose_name="学习目标",
            ),
        ),
        migrations.AlterField(
            model_name="learningsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="wordlearningrecord",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_records",
                to="teaching.learninggoal",
                verbose_name="学习目标",
            ),
        ),
        migrations.AlterField(
            model_name="wordlearningrecord",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_records",
                to="words.word",
                verbose_name="单词",
            ),
        ),
    ]
