# Generated by Django 4.2.7 on 2025-08-10 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0002_wordgradelevel_wordgrader_wordset_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teaching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learninggoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("vocabulary", "词汇学习"),
                    ("reading", "阅读理解"),
                    ("listening", "听力训练"),
                    ("speaking", "口语练习"),
                    ("writing", "写作训练"),
                ],
                default="vocabulary",
                max_length=20,
                verbose_name="目标类型",
            ),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="vocabulary_lists",
            field=models.ManyToManyField(
                blank=True,
                help_text="选择要学习的词汇表",
                related_name="teaching_learning_goals",
                to="words.vocabularylist",
                verbose_name="词汇表",
            ),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="word_sets",
            field=models.ManyToManyField(
                blank=True,
                help_text="选择要学习的单词集",
                related_name="teaching_learning_goals",
                to="words.wordset",
                verbose_name="单词集",
            ),
        ),
        migrations.AddField(
            model_name="wordlearningrecord",
            name="is_forgotten",
            field=models.BooleanField(default=False, verbose_name="是否遗忘"),
        ),
        migrations.AlterField(
            model_name="learningplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("mechanical", "机械模式 - 固定每日学习量，不考虑学习进展更新"),
                    ("daily_progress", "日进模式 - 根据学习进展每日更新，按剩余时间均分"),
                    ("weekday", "工作日模式 - 只在工作日学习，按剩余工作日均分"),
                    ("weekend", "周末模式 - 只在周末学习，按剩余周末天数均分"),
                    ("daily", "每日计划 - 标准每日学习计划"),
                    ("weekly", "每周计划 - 按周制定学习计划"),
                    ("custom", "自定义计划 - 用户自定义学习节奏"),
                ],
                default="daily",
                max_length=20,
                verbose_name="计划类型",
            ),
        ),
        migrations.CreateModel(
            name="GuidedPracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        default="guided_practice", max_length=50, verbose_name="会话类型"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("total_questions", models.IntegerField(default=0, verbose_name="总题数")),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="正确答案数"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teaching.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "引导练习会话",
                "verbose_name_plural": "引导练习会话",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="GuidedPracticeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "选择题"),
                            ("fill_blank", "填空题"),
                            ("translation", "翻译题"),
                            ("pronunciation", "发音题"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="问题类型",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="问题内容")),
                (
                    "correct_answer",
                    models.CharField(max_length=200, verbose_name="正确答案"),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="选项"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="teaching.guidedpracticesession",
                        verbose_name="练习会话",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="words.word",
                        verbose_name="单词",
                    ),
                ),
            ],
            options={
                "verbose_name": "引导练习问题",
                "verbose_name_plural": "引导练习问题",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuidedPracticeAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(max_length=200, verbose_name="用户答案")),
                ("is_correct", models.BooleanField(verbose_name="是否正确")),
                ("response_time", models.FloatField(verbose_name="响应时间（秒）")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="teaching.guidedpracticequestion",
                        verbose_name="问题",
                    ),
                ),
            ],
            options={
                "verbose_name": "引导练习答案",
                "verbose_name_plural": "引导练习答案",
                "ordering": ["-created_at"],
            },
        ),
    ]
