# Generated by Django 4.2.7 on 2025-08-10 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0003_word_book_volume_word_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "teaching",
            "0002_learninggoal_goal_type_learninggoal_vocabulary_lists_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_date",
                    models.DateField(blank=True, null=True, verbose_name="学习日期"),
                ),
                ("target_words", models.IntegerField(default=0, verbose_name="目标单词数")),
                (
                    "completed_words",
                    models.IntegerField(default=0, verbose_name="完成单词数"),
                ),
                (
                    "study_duration",
                    models.DurationField(blank=True, null=True, verbose_name="学习时长"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "每日学习记录",
                "verbose_name_plural": "每日学习记录",
                "ordering": ["-study_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="learninggoal",
            options={
                "ordering": ["-is_current", "-created_at"],
                "verbose_name": "学习目标",
                "verbose_name_plural": "学习目标",
            },
        ),
        migrations.AlterModelOptions(
            name="learningplan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
            },
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="words.wordgradelevel",
                verbose_name="分级等级",
            ),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="是否为当前目标"),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="learned_words",
            field=models.IntegerField(default=0, verbose_name="已学单词数"),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="total_words",
            field=models.IntegerField(default=0, verbose_name="总单词数"),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="vocabulary_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_learning_goals",
                to="words.vocabularylist",
                verbose_name="词库列表",
            ),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="word_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_learning_goals",
                to="words.wordset",
                verbose_name="词集",
            ),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="daily_target",
            field=models.IntegerField(default=0, verbose_name="每日目标单词数"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="name",
            field=models.CharField(default=1, max_length=100, verbose_name="计划名称"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningplan",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="开始日期"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "进行中"),
                    ("completed", "已完成"),
                    ("paused", "已暂停"),
                    ("cancelled", "已取消"),
                ],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="total_words",
            field=models.IntegerField(default=0, verbose_name="总单词数"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_learning_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="learninggoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("vocabulary_list", "词库"),
                    ("word_set", "词集"),
                    ("grade_level", "分级"),
                    ("vocabulary", "词汇学习"),
                    ("reading", "阅读理解"),
                    ("listening", "听力训练"),
                    ("speaking", "口语练习"),
                    ("writing", "写作训练"),
                ],
                default="vocabulary",
                max_length=20,
                verbose_name="目标类型",
            ),
        ),
        migrations.AlterField(
            model_name="learninggoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_learning_goals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="learninggoal",
            name="vocabulary_lists",
            field=models.ManyToManyField(
                blank=True,
                help_text="选择要学习的词汇表",
                related_name="teaching_multi_goals",
                to="words.vocabularylist",
                verbose_name="词汇表",
            ),
        ),
        migrations.AlterField(
            model_name="learninggoal",
            name="word_sets",
            field=models.ManyToManyField(
                blank=True,
                help_text="选择要学习的单词集",
                related_name="teaching_multi_goals",
                to="words.wordset",
                verbose_name="单词集",
            ),
        ),
        migrations.AlterField(
            model_name="learningplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("mechanical", "机械模式"),
                    ("daily_progress", "日进模式"),
                    ("weekday", "工作日模式"),
                    ("weekend", "周末模式"),
                    ("daily", "每日计划"),
                    ("weekly", "每周计划"),
                    ("custom", "自定义计划"),
                ],
                default="daily",
                max_length=20,
                verbose_name="计划类型",
            ),
        ),
        migrations.AddIndex(
            model_name="learninggoal",
            index=models.Index(
                fields=["user", "is_current"], name="teaching_le_user_id_591d79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learninggoal",
            index=models.Index(
                fields=["goal_type"], name="teaching_le_goal_ty_a440a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningplan",
            index=models.Index(
                fields=["user", "status"], name="teaching_le_user_id_42c730_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningplan",
            index=models.Index(fields=["goal"], name="teaching_le_goal_id_29c9a9_idx"),
        ),
        migrations.AddIndex(
            model_name="learningplan",
            index=models.Index(
                fields=["start_date", "end_date"], name="teaching_le_start_d_19fba7_idx"
            ),
        ),
        migrations.AddField(
            model_name="dailystudyrecord",
            name="learning_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_records",
                to="teaching.learningplan",
                verbose_name="学习计划",
            ),
        ),
        migrations.AddField(
            model_name="dailystudyrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_daily_study_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="dailystudyrecord",
            index=models.Index(
                fields=["user", "study_date"], name="teaching_da_user_id_3be007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailystudyrecord",
            index=models.Index(
                fields=["learning_plan", "study_date"],
                name="teaching_da_learnin_5507b6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystudyrecord",
            unique_together={("user", "learning_plan", "study_date")},
        ),
    ]
