# Generated by Django 4.2.7 on 2025-08-05 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0008_remove_word_words_word_has_con_613e5b_idx_and_more'),
        ('teaching', '0002_alter_goalword_word_alter_learningsession_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='列表名称')),
                ('list_type', models.CharField(choices=[('new_words', '生词列表'), ('known_words', '熟词列表')], max_length=20, verbose_name='列表类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_lists', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '词汇列表',
                'verbose_name_plural': '词汇列表',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('vocabulary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='teaching.vocabularylist', verbose_name='词汇列表')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_associations', to='words.word', verbose_name='单词')),
            ],
            options={
                'verbose_name': '词汇单词',
                'verbose_name_plural': '词汇单词',
                'ordering': ['-added_at'],
                'unique_together': {('vocabulary_list', 'word')},
            },
        ),
    ]
