# Generated by Django 4.2.7 on 2025-08-09 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teaching", "0003_vocabularylist_vocabularyword"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vocabularyword",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="vocabularyword",
            name="vocabulary_list",
        ),
        migrations.RemoveField(
            model_name="vocabularyword",
            name="word",
        ),
        migrations.DeleteModel(
            name="VocabularyList",
        ),
        migrations.DeleteModel(
            name="VocabularyWord",
        ),
    ]
