# Generated by Django 4.2.7 on 2025-08-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0009_remove_conflict_resolution"),
        ("teaching", "0004_alter_vocabularyword_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learninggoal",
            name="vocabulary_lists",
            field=models.ManyToManyField(
                blank=True,
                related_name="teaching_goals",
                to="words.vocabularylist",
                verbose_name="关联单词库",
            ),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="word_sets",
            field=models.ManyToManyField(
                blank=True,
                related_name="teaching_goals",
                to="words.wordset",
                verbose_name="关联单词集",
            ),
        ),
    ]
