# Generated by Django 4.2.7 on 2025-08-09 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teaching", "0002_alter_goalword_word_alter_learningsession_goal_and_more"),
        ("teaching", "0005_learninggoal_vocabulary_lists_learninggoal_word_sets"),
    ]

    operations = []
