# Generated by Django 4.2.7 on 2025-08-09 23:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0009_remove_conflict_resolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teaching", "0007_add_guided_practice_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningplan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
            },
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("vocabulary_list", "词库"),
                    ("word_set", "词集"),
                    ("grade_level", "分级"),
                    ("mixed", "混合"),
                ],
                default="mixed",
                max_length=20,
                verbose_name="目标类型",
            ),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="是否为当前目标"),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="learned_words",
            field=models.IntegerField(default=0, verbose_name="已学单词数"),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="total_words",
            field=models.IntegerField(default=0, verbose_name="总单词数"),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="vocabulary_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="single_learning_goals",
                to="words.vocabularylist",
                verbose_name="单一词库列表",
            ),
        ),
        migrations.AddField(
            model_name="learninggoal",
            name="word_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="single_learning_goals",
                to="words.wordset",
                verbose_name="单一词集",
            ),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="completed_days",
            field=models.IntegerField(default=0, verbose_name="已完成天数"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="daily_study_time",
            field=models.DurationField(
                default=datetime.timedelta(seconds=1800), verbose_name="每日学习时长"
            ),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="description",
            field=models.TextField(blank=True, verbose_name="计划描述"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "简单"), ("medium", "中等"), ("hard", "困难")],
                default="medium",
                max_length=20,
                verbose_name="难度等级",
            ),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="name",
            field=models.CharField(default=1, max_length=200, verbose_name="计划名称"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningplan",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="开始日期"
            ),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="total_days",
            field=models.IntegerField(default=0, verbose_name="总天数"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="learningplan",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_learning_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningsession",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="学习时长"),
        ),
        migrations.AddField(
            model_name="learningsession",
            name="words_learned",
            field=models.IntegerField(default=0, verbose_name="掌握单词数"),
        ),
        migrations.AlterField(
            model_name="learningplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("daily", "每日计划"),
                    ("weekly", "每周计划"),
                    ("monthly", "每月计划"),
                    ("custom", "自定义计划"),
                ],
                default="daily",
                max_length=20,
                verbose_name="计划类型",
            ),
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="当前连续天数"),
                ),
                (
                    "longest_streak",
                    models.IntegerField(default=0, verbose_name="最长连续天数"),
                ),
                (
                    "last_study_date",
                    models.DateField(blank=True, null=True, verbose_name="最后学习日期"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_streak",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户连续学习记录",
                "verbose_name_plural": "用户连续学习记录",
            },
        ),
        migrations.CreateModel(
            name="WordLearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("new", "新单词"),
                            ("learning", "学习中"),
                            ("reviewing", "复习中"),
                            ("mastered", "已掌握"),
                            ("forgotten", "已遗忘"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="掌握程度",
                    ),
                ),
                ("correct_count", models.IntegerField(default=0, verbose_name="正确次数")),
                (
                    "total_attempts",
                    models.IntegerField(default=0, verbose_name="总尝试次数"),
                ),
                (
                    "first_learned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="首次学习时间"),
                ),
                (
                    "last_reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后复习时间"),
                ),
                (
                    "next_review_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次复习时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_progress",
                        to="teaching.learninggoal",
                        verbose_name="学习目标",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_word_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="words.word",
                        verbose_name="单词",
                    ),
                ),
            ],
            options={
                "verbose_name": "单词学习进度",
                "verbose_name_plural": "单词学习进度",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "word", "goal")},
            },
        ),
        migrations.CreateModel(
            name="DailyStudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("words_studied", models.IntegerField(default=0, verbose_name="学习单词数")),
                ("words_learned", models.IntegerField(default=0, verbose_name="掌握单词数")),
                (
                    "study_time",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="学习时长"
                    ),
                ),
                (
                    "sessions_count",
                    models.IntegerField(default=0, verbose_name="学习会话数"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_daily_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日学习记录",
                "verbose_name_plural": "每日学习记录",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
